BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Affiliations')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u"Learn about Bhanjyang Cooperative's affiliations with regulatory bodies, professional associations, and partnerships that ensure our compliance and excellence.") BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Affiliations')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u"Learn about Bhanjyang Cooperative's affiliations with regulatory bodies, professional associations, and partnerships.") BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBBXXXXXXXBBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBBBB gettext(u'Affiliations')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB gettext(u"Learn about Bhanjyang Cooperative's affiliations with regulatory bodies and professional associations.") BBBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB


BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX gettext(u'Our Affiliations') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'We are proud to be associated with these organizations and regulatory bodies, including our local regulatory authority Rupa Rural Municipality.') XXXX
    XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                BBB BBBBBBBBBBB BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXFFFFFFFXXXX
                    BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXX
                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                    BBBBB
                    
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXX
                            
                        XXXXXXX
                    XXXXXX
                    
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                        XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                             gettext(u'Visit Website') 
                        XXXX
                    BBBBB
                XXXXXX
                BBBBBB
            XXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'No affiliations are available yet.') XXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Affiliation information will be added as it becomes available.') XXXX
            XXXXXX
        BBBBB
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXXX XXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Types of Affiliations') XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX gettext(u'Understanding our various partnerships and regulatory relationships.') XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Regulatory Bodies') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Government agencies that oversee cooperative operations and ensure compliance.') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Professional Associations') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Industry organizations that promote best practices and professional development.') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Partnerships') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Strategic collaborations that enhance our services and community impact.') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Certification Bodies') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Organizations that provide certifications and quality assurance standards.') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Umbrella Organizations') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Parent organizations that coordinate and support multiple cooperatives and institutions.') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Cooperative Banks') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Financial institutions that provide banking services and support to cooperatives.') XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB
