BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Board of Directors')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Meet the Board of Directors and committees of Bhanjyang Saving & Credit Cooperative Society Ltd. Learn about our elected leadership and governance structure.') BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXX XXXXX XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Board of Directors')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u'Meet the Board of Directors and committees of Bhanjyang Cooperative. Learn about our elected leadership and governance structure.') BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBBXXXXXXXBBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBBBB gettext(u'Board of Directors')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB gettext(u'Meet the Board of Directors and committees of Bhanjyang Cooperative. Learn about our elected leadership and governance structure.') BBBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXX XXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Governance') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Board of Directors') 
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u"Meet our elected leadership who guide our cooperative's vision and governance") 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBB
            XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Committee') 
                    XXXXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                        
                    XXXXX
                    XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Tenure:') XXXXXXX 
                    XXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                        
                    XXXX
                    BBBBB
                XXXXXX
                
                BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXX XXXXXX 
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
                
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX 
                                 XXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX 
                                 XXXXXXXXXX XX X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXX
                        BBBBB
                    XXXXXX
                    BBBBB
                    BBBBBB
                XXXXXX
            XXXXXX
        BBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'No Board Information Available') XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Board of Directors information will be available soon.') XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX 
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX gettext(u'Back to About Us') XXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
        BBBBBB
    XXXXXX
XXXXXXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXX XXXXXXXXXX XXXX XXXXXXXXX XXX XXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBB

