BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Management Team')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Meet the Management Team of Bhanjyang Saving & Credit Cooperative Society Ltd. Professional staff members who handle day-to-day operations and member services.') BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Management Team')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u'Meet the Management Team of Bhanjyang Cooperative. Professional staff members who handle day-to-day operations and member services.') BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBBXXXXXXXBBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBBBB gettext(u'Management Team')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB gettext(u'Meet the Management Team of Bhanjyang Cooperative. Professional staff members who handle day-to-day operations and member services.') BBBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXX XXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Operations') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Management Team') 
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Professional staff members who handle day-to-day operations and member services') 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXX XXXX XXXXXXX XXX
BB BBBBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX 
                         XXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX 
                         XXXXXXXXXX XX X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX 
                       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX
                XXXXXX
                BBBBB
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBB
XXXX XX XXXXXXXXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'No Management Team Information Available') XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Management team information will be available soon.') XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX 
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Back to About Us') XXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB

BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXX XXXXXXXXXX XXXX XXXXXXXXX XXX XXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBB

