BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Timeline')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Explore the timeline of Bhanjyang Saving & Credit Cooperative Society Ltd. Discover our key milestones, achievements, and growth journey over the years.') BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Timeline')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u'Explore the timeline of Bhanjyang Cooperative. Discover our key milestones, achievements, and growth journey over the years.') BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBBXXXXXXXBBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBBBB gettext(u'Timeline')  X XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB gettext(u'Explore the timeline of Bhanjyang Cooperative. Discover our key milestones and achievements.') BBBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXX XXXXXX
        XXXXXXX XXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
        XXXXXXXX XXX
    X

    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXX XXX
    X

    XXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXX XXXX XXXX XXX XXXXX XX XXXX XX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X

    XX XXXXXX XXXXXXX XXXXXXX XX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XX XXXXXXXXXX XXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXX X
            XXXXXXX XXXX XX
        X
    X
XXXXXXXX

XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Our Journey') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
             gettext(u'Timeline Infographic') 
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Explore our key milestones, achievements, and growth journey over the years') 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXX XXXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXX

            BBB BBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXX BBBB XXXXXX BBBBB XXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXX XXXX XXXX XXXXXXXXX XXX
                BB BBB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXX XXX XXXXXXXXXXX XXXXXXXXXXXXX
                BBBBB

                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBB BBBBB BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBB BBBB XXXXXXXXXXX BBBBBXX

                    BB BBBBBBBBBBB
                    XXXX XXXXXXXXXX XXXXX XXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXX XXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBB

                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXX
                        XXXX XXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBB BBBBBBBBBB XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX

                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            
                        XXXXX

                        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF
                        XXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXX XXXX XXXXX XXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBB
                XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
            XXXXXX
            BBBBBB
        XXXXXX

        XXXX XXXXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                XX XXXXXXXXXXXXX
                    XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX
                BBBBB

                XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX  XX 
                XXXXXXX

                BB BBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXX
                    XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                XX XXXXXXXXXXXXX
                    XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                BBBBB
            XXXXXX
        XXXXXX
        BBBBB

        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'No Timeline Events') XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'No timeline events are available yet.') XXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Timeline information will be added as it becomes available.') XXXX
            XXXXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXX XXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXXX XXXX
        XXXXXXXXXXX XXXX XXX XXXXXX XXXX
    XX

    XXXXX XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXX XXXXXXX XXX XXXXXXXXX XX XX XXXXXX
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXX X
                    XXXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXX
                X
                XX XXXX XXXXXXXXX XXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XXX XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
        XX XXX XXXXXXXXX XXXXX XXXXX XX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XX XXX XXXXXXXX XXXXXX XX XXXXXXXX XXXXXXXXX XX XXXXXX
    XXX XXXXXXX X XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXX X XXXX
            XXXXX XXXX X XXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXXXXX X XXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX X XXXXX
        X
    X

    XX XXXX XXXXX XXXXXXXX XX XXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXX X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    X
XXX
XXXXXXXXX

XXXX XXXXXXXXXX XXXX XXXXXXXXX XXX XXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBB
