# Generated by Django 5.2.3 on 2025-10-16 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_data', models.JSONField()),
                ('summary', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('404', 'Page Not Found'), ('500', 'Server Error'), ('template', 'Template Error'), ('database', 'Database Error'), ('validation', 'Validation Error'), ('permission', 'Permission Error'), ('timeout', 'Timeout Error')], max_length=20)),
                ('error_message', models.TextField()),
                ('page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['error_type', 'timestamp'], name='performance_error_t_9f7f29_idx'), models.Index(fields=['resolved', 'timestamp'], name='performance_resolve_ae7bf8_idx'), models.Index(fields=['timestamp'], name='performance_timesta_1d676b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('load_time', models.FloatField(help_text='Page load time in milliseconds')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mobile', models.BooleanField(default=False)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['page_url', 'timestamp'], name='performance_page_ur_7cc6a1_idx'), models.Index(fields=['timestamp'], name='performance_timesta_fbb432_idx'), models.Index(fields=['is_mobile'], name='performance_is_mobi_b9eb12_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('page_load', 'Page Load Time'), ('image_load', 'Image Load Time'), ('search_time', 'Search Response Time'), ('form_submit', 'Form Submission Time'), ('api_response', 'API Response Time'), ('database_query', 'Database Query Time'), ('memory_usage', 'Memory Usage'), ('cpu_usage', 'CPU Usage')], max_length=20)),
                ('page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('value', models.FloatField(help_text='Metric value (e.g., milliseconds, bytes)')),
                ('unit', models.CharField(default='ms', help_text='Unit of measurement', max_length=20)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='performance_metric__b34494_idx'), models.Index(fields=['page_url', 'timestamp'], name='performance_page_ur_05a474_idx'), models.Index(fields=['timestamp'], name='performance_timesta_c5241b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('total_load_time', models.FloatField(default=0)),
                ('is_mobile', models.BooleanField(default=False)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['session_id'], name='performance_session_f0c26c_idx'), models.Index(fields=['start_time'], name='performance_start_t_a41646_idx'), models.Index(fields=['user', 'start_time'], name='performance_user_id_3ed7f0_idx')],
            },
        ),
    ]
