# Generated by Django 5.2.7 on 2025-10-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='dashboard_e_error_t_8205a1_idx',
            old_name='performance_error_t_9f7f29_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='dashboard_e_resolve_6a99a9_idx',
            old_name='performance_resolve_ae7bf8_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='dashboard_e_timesta_361f7d_idx',
            old_name='performance_timesta_1d676b_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='dashboard_p_page_ur_1d00a1_idx',
            old_name='performance_page_ur_7cc6a1_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='dashboard_p_timesta_ebd61e_idx',
            old_name='performance_timesta_fbb432_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='dashboard_p_is_mobi_59a531_idx',
            old_name='performance_is_mobi_b9eb12_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='dashboard_p_metric__974d4f_idx',
            old_name='performance_metric__b34494_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='dashboard_p_page_ur_78c16b_idx',
            old_name='performance_page_ur_05a474_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='dashboard_p_timesta_8457a3_idx',
            old_name='performance_timesta_c5241b_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='dashboard_u_session_019601_idx',
            old_name='performance_session_f0c26c_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='dashboard_u_start_t_4724d1_idx',
            old_name='performance_start_t_a41646_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='dashboard_u_user_id_a74972_idx',
            old_name='performance_user_id_3ed7f0_idx',
        ),
    ]
