# Generated by Django 5.2.7 on 2025-10-19 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardwidget_performancealert_alertlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('dashboard_access', 'Dashboard Access'), ('data_export', 'Data Export'), ('alert_resolve', 'Alert Resolution'), ('preference_update', 'Preference Update'), ('admin_access', 'Admin Access'), ('suspicious_activity', 'Suspicious Activity')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='dashboard_a_user_id_15b85a_idx'), models.Index(fields=['action_type', 'timestamp'], name='dashboard_a_action__28eced_idx'), models.Index(fields=['ip_address', 'timestamp'], name='dashboard_a_ip_addr_436d62_idx')],
            },
        ),
    ]
