# Generated by Django 5.2.7 on 2025-10-20 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['view_count'], name='news_events_view_co_16ee44_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='news_events_created_7039ed_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['updated_at'], name='news_events_updated_978d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_date'], name='news_events_end_dat_8f7629_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='news_events_locatio_48e24b_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['status', 'published_date', 'is_featured'], name='news_events_status_bfb8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category', 'status', 'published_date'], name='news_events_categor_404c02_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['view_count'], name='news_events_view_co_87a410_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['created_at'], name='news_events_created_ef01ff_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['updated_at'], name='news_events_updated_f2a310_idx'),
        ),
    ]
