# Generated by Django 5.2.9 on 2026-01-03 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_events", "0002_event_news_events_view_co_16ee44_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "श्रेणी",
                "verbose_name_plural": "श्रेणीहरू",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "टिप्पणी",
                "verbose_name_plural": "टिप्पणीहरू",
            },
        ),
        migrations.AlterModelOptions(
            name="contentanalytics",
            options={
                "ordering": ["-date"],
                "verbose_name": "सामग्री विश्लेषण",
                "verbose_name_plural": "सामग्री विश्लेषणहरू",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["event_date"],
                "verbose_name": "कार्यक्रम",
                "verbose_name_plural": "कार्यक्रमहरू",
            },
        ),
        migrations.AlterModelOptions(
            name="newsarticle",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "समाचार लेख",
                "verbose_name_plural": "समाचार लेखहरू",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "न्युजलेटर",
                "verbose_name_plural": "न्युजलेटरहरू",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ["-subscribed_at"],
                "verbose_name": "सदस्य",
                "verbose_name_plural": "सदस्यहरू",
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="failed_recipients",
            field=models.TextField(
                blank=True,
                help_text="इमेल पठाउन असफल भएका प्रापकहरूको सूची (JSON format)",
                verbose_name="असफल प्रापकहरू",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#28A745",
                help_text="श्रेणीको हेक्स रङ कोड",
                max_length=7,
                verbose_name="रङ",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="श्रेणीको विवरण", verbose_name="विवरण"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="FontAwesome आइकन क्लास",
                max_length=50,
                verbose_name="आइकन",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="यो श्रेणी सक्रिय छ कि छैन", verbose_name="सक्रिय"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="श्रेणीको नाम", max_length=100, unique=True, verbose_name="नाम"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-अनुकूल संस्करण",
                max_length=100,
                unique=True,
                verbose_name="स्लग",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="प्रदर्शनको लागि क्रम", verbose_name="क्रम"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                help_text="सम्बन्धित लेख",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news_events.newsarticle",
                verbose_name="लेख",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_email",
            field=models.EmailField(
                help_text="टिप्पणी लेखकको इमेल", max_length=254, verbose_name="लेखकको इमेल"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(
                help_text="टिप्पणी लेखकको नाम", max_length=100, verbose_name="लेखकको नाम"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(help_text="टिप्पणी सामग्री", verbose_name="सामग्री"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP ठेगाना", null=True, verbose_name="IP ठेगाना"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="टिप्पणी अनुमोदित", verbose_name="अनुमोदित"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="like_count",
            field=models.PositiveIntegerField(
                default=0, help_text="मन पराइएको संख्या", verbose_name="मन पराइएको संख्या"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निरीक्षण गरेको",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="निरीक्षण गरेको",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="moderation_notes",
            field=models.TextField(
                blank=True, help_text="निरीक्षण नोट", verbose_name="निरीक्षण नोट"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PEN", "अनुमोदन पछि"),
                    ("APP", "अनुमोदित"),
                    ("REJ", "अस्वीकृत"),
                    ("SPA", "स्प्याम"),
                ],
                default="PEN",
                help_text="टिप्पणी स्थिति",
                max_length=3,
                verbose_name="स्थिति",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="प्रयोगकर्ता एजेन्ट", verbose_name="प्रयोगकर्ता एजेन्ट"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="comments",
            field=models.PositiveIntegerField(
                default=0, help_text="टिप्पणीको संख्या", verbose_name="टिप्पणी"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="content_id",
            field=models.PositiveIntegerField(
                help_text="सामग्री ID", verbose_name="सामग्री ID"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="content_type",
            field=models.CharField(
                help_text="सामग्री प्रकार (लेख, कार्यक्रम)",
                max_length=20,
                verbose_name="सामग्री प्रकार",
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="date",
            field=models.DateField(help_text="विश्लेषण मिति", verbose_name="मिति"),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="direct_traffic",
            field=models.PositiveIntegerField(
                default=0, help_text="प्रत्यक्ष ट्राफिक हेराइ", verbose_name="प्रत्यक्ष ट्राफिक"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="organic_search",
            field=models.PositiveIntegerField(
                default=0, help_text="जैविक खोज हेराइ", verbose_name="जैविक खोज"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="referral_traffic",
            field=models.PositiveIntegerField(
                default=0, help_text="रेफरल ट्राफिक हेराइ", verbose_name="रेफरल ट्राफिक"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="shares",
            field=models.PositiveIntegerField(
                default=0, help_text="साझेदारीको संख्या", verbose_name="साझेदारी"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="social_media",
            field=models.PositiveIntegerField(
                default=0,
                help_text="सामाजिक मिडिया हेराइ",
                verbose_name="सामाजिक मिडिया",
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="time_on_page",
            field=models.FloatField(
                default=0, help_text="पृष्ठमा औसत समय (सेकेन्डमा)", verbose_name="पृष्ठमा समय"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="unique_views",
            field=models.PositiveIntegerField(
                default=0, help_text="अद्वितीय हेराइको संख्या", verbose_name="अद्वितीय हेराइ"
            ),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="views",
            field=models.PositiveIntegerField(
                default=0, help_text="हेराइको संख्या", verbose_name="हेराइ"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.TextField(
                blank=True, help_text="पूर्ण कार्यक्रम ठेगाना", verbose_name="ठेगाना"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(help_text="कार्यक्रमको विवरण", verbose_name="विवरण"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="कार्यक्रम अन्त्य मिति र समय",
                null=True,
                verbose_name="अन्त्य मिति",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(
                help_text="कार्यक्रम मिति र समय", verbose_name="कार्यक्रम मिति"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("MEET", "बैठक"),
                    ("WORK", "कार्यशाला"),
                    ("CONF", "सम्मेलन"),
                    ("SEMI", "सेमिनार"),
                    ("SOC", "सामाजिक कार्यक्रम"),
                    ("TRAIN", "प्रशिक्षण"),
                    ("OTH", "अन्य"),
                ],
                default="OTH",
                help_text="कार्यक्रमको प्रकार",
                max_length=5,
                verbose_name="कार्यक्रम प्रकार",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="कार्यक्रम छवि",
                null=True,
                upload_to="news_events/events/",
                verbose_name="छवि",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="छविको Alt पाठ",
                max_length=200,
                verbose_name="छवि Alt पाठ",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="मुख्य कार्यक्रम", verbose_name="मुख्य"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(
                default=False, help_text="पुनरावृत्ति हुने कार्यक्रम", verbose_name="पुनरावृत्ति"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True,
                help_text="अन्तिम पहुँच समय",
                null=True,
                verbose_name="अन्तिम पहुँच मिति",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                default="Cooperative Office",
                help_text="कार्यक्रम स्थान",
                max_length=150,
                verbose_name="स्थान",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_attendees",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="अधिकतम सहभागी संख्या",
                null=True,
                verbose_name="अधिकतम सहभागी",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="दर्ताको संख्या",
                verbose_name="दर्ता संख्या",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="दर्ता अन्तिम मिति",
                null=True,
                verbose_name="दर्ता अन्तिम मिति",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_required",
            field=models.BooleanField(
                default=False, help_text="दर्ता आवश्यक", verbose_name="दर्ता आवश्यक"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_url",
            field=models.URLField(
                blank=True, help_text="दर्ता URL", verbose_name="दर्ता URL"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="छोटो कार्यक्रम विवरण",
                max_length=300,
                verbose_name="छोटो विवरण",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-अनुकूल शीर्षक",
                max_length=250,
                unique=True,
                verbose_name="स्लग",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "मस्यौदा"),
                    ("PB", "प्रकाशित"),
                    ("CAN", "रद्द"),
                    ("COM", "पूर्ण"),
                ],
                default="DF",
                help_text="कार्यक्रम स्थिति",
                max_length=3,
                verbose_name="स्थिति",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                help_text="कार्यक्रमको शीर्षक", max_length=200, verbose_name="शीर्षक"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
        ),
        migrations.AlterField(
            model_name="event",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="हेराइको संख्या",
                verbose_name="हेराइ संख्या",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="allow_comments",
            field=models.BooleanField(
                default=True,
                help_text="टिप्पणी अनुमति दिनुहोस्",
                verbose_name="टिप्पणी अनुमति",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="author",
            field=models.ForeignKey(
                help_text="लेखको लेखक",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_events_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="लेखक",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="category",
            field=models.ForeignKey(
                help_text="लेखको श्रेणी",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="news_events.category",
                verbose_name="श्रेणी",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="comment_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="टिप्पणीको संख्या",
                verbose_name="टिप्पणी संख्या",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(help_text="लेखको सामग्री", verbose_name="सामग्री"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="content_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="सामग्रीको SHA-256 ह्यास",
                max_length=64,
                verbose_name="सामग्री ह्यास",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="छोटो लेख सारांश",
                max_length=500,
                verbose_name="सारांश",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="मुख्य छवि",
                null=True,
                upload_to="news_events/images/",
                verbose_name="छवि",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="छविको Alt पाठ",
                max_length=200,
                verbose_name="छवि Alt पाठ",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="मुख्य लेख", verbose_name="मुख्य"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True,
                help_text="अन्तिम पहुँच समय",
                null=True,
                verbose_name="अन्तिम पहुँच मिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="SEO विवरण",
                max_length=300,
                verbose_name="SEO विवरण",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="SEO कीवर्ड",
                max_length=500,
                verbose_name="SEO कीवर्ड",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO शीर्षक",
                max_length=200,
                verbose_name="SEO शीर्षक",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "न्यून प्राथमिकता"),
                    ("MED", "मध्यम प्राथमिकता"),
                    ("HIGH", "उच्च प्राथमिकता"),
                    ("URG", "तत्काल"),
                ],
                default="MED",
                help_text="सामग्री प्राथमिकता",
                max_length=4,
                verbose_name="प्राथमिकता",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="प्रकाशन मिति",
                verbose_name="प्रकाशन मिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="read_time",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="अनुमानित पढ्ने समय (मिनेटमा)",
                verbose_name="पढ्ने समय",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="require_login",
            field=models.BooleanField(
                default=False,
                help_text="हेर्नको लागि लगइन आवश्यक",
                verbose_name="लगइन आवश्यक",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="तालिकाबद्ध प्रकाशन मिति",
                null=True,
                verbose_name="तालिकाबद्ध मिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="share_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="साझेदारीको संख्या",
                verbose_name="साझेदारी संख्या",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-अनुकूल शीर्षक",
                max_length=250,
                unique=True,
                verbose_name="स्लग",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "मस्यौदा"),
                    ("PB", "प्रकाशित"),
                    ("AR", "संग्रह"),
                    ("SC", "तालिकाबद्ध"),
                ],
                default="DF",
                help_text="प्रकाशन स्थिति",
                max_length=2,
                verbose_name="स्थिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.CharField(
                help_text="लेखको शीर्षक", max_length=200, verbose_name="शीर्षक"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="हेराइको संख्या",
                verbose_name="हेराइ संख्या",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="लक्ष्य श्रेणीहरू",
                to="news_events.category",
                verbose_name="लक्ष्य श्रेणी",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="content",
            field=models.TextField(help_text="न्युजलेटर सामग्री", verbose_name="सामग्री"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="तालिकाबद्ध पठाउने मिति",
                null=True,
                verbose_name="तालिकाबद्ध मिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="send_to_all",
            field=models.BooleanField(
                default=True,
                help_text="सबै सदस्यहरूलाई पठाउनुहोस्",
                verbose_name="सबैलाई पठाउनुहोस्",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="sent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="वास्तविक पठाउने मिति",
                null=True,
                verbose_name="पठाइएको मिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "मस्यौदा"),
                    ("SC", "तालिकाबद्ध"),
                    ("SE", "पठाइरहेको"),
                    ("SN", "पठाइएको"),
                    ("FA", "असफल"),
                ],
                default="DF",
                help_text="न्युजलेटर स्थिति",
                max_length=2,
                verbose_name="स्थिति",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="subject",
            field=models.CharField(
                help_text="इमेल विषय", max_length=200, verbose_name="विषय"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="title",
            field=models.CharField(
                help_text="न्युजलेटर शीर्षक", max_length=200, verbose_name="शीर्षक"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="total_clicked",
            field=models.PositiveIntegerField(
                default=0,
                help_text="कुल क्लिक गरिएको लिङ्क",
                verbose_name="कुल क्लिक गरिएको",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="total_opened",
            field=models.PositiveIntegerField(
                default=0, help_text="कुल खोलिएको इमेल", verbose_name="कुल खोलिएको"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="total_sent",
            field=models.PositiveIntegerField(
                default=0, help_text="कुल पठाइएको इमेल", verbose_name="कुल पठाइएको"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="प्राथमिकता श्रेणीहरू",
                to="news_events.category",
                verbose_name="प्राथमिकता श्रेणी",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="click_count",
            field=models.PositiveIntegerField(
                default=0, help_text="क्लिक गरिएको लिङ्क संख्या", verbose_name="क्लिक संख्या"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="confirmation_token",
            field=models.CharField(
                blank=True,
                help_text="इमेल पुष्टिकरण टोकन",
                max_length=64,
                verbose_name="पुष्टिकरण टोकन",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="इमेल पुष्टि मिति",
                null=True,
                verbose_name="पुष्टि मिति",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(
                help_text="सदस्यको इमेल", max_length=254, unique=True, verbose_name="इमेल"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="पहिलो नाम",
                max_length=100,
                verbose_name="पहिलो नाम",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="frequency",
            field=models.CharField(
                default="weekly",
                help_text="इमेल आवृत्ति प्राथमिकता",
                max_length=20,
                verbose_name="आवृत्ति",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="सदस्यता लिँदा IP ठेगाना",
                null=True,
                verbose_name="IP ठेगाना",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, help_text="इमेल पुष्टि भएको", verbose_name="पुष्टि भएको"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                help_text="अन्तिम गतिविधि मिति",
                null=True,
                verbose_name="अन्तिम गतिविधि मिति",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="अन्तिम नाम",
                max_length=100,
                verbose_name="अन्तिम नाम",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="open_count",
            field=models.PositiveIntegerField(
                default=0, help_text="खोलिएको इमेल संख्या", verbose_name="खोलिएको संख्या"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACT", "सक्रिय"),
                    ("UNS", "सदस्यता रद्द"),
                    ("BOU", "बाउन्स"),
                    ("SPA", "स्प्याम"),
                ],
                default="ACT",
                help_text="सदस्यता स्थिति",
                max_length=3,
                verbose_name="स्थिति",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="subscribed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="सदस्यता मिति"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="सदस्यता लिँदा प्रयोगकर्ता एजेन्ट",
                verbose_name="प्रयोगकर्ता एजेन्ट",
            ),
        ),
    ]
