# Generated by Django 5.2.9 on 2026-01-17 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_events", "0003_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopupNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Popup notice को शीर्षक (e.g., '14th Annual General Meeting Notice')",
                        max_length=200,
                        verbose_name="शीर्षक",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Notice को छोटो विवरण (optional)",
                        verbose_name="विवरण",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("agm", "वार्षिक साधारण सभा (AGM)"),
                            ("egm", "असाधारण साधारण सभा (EGM)"),
                            ("general", "सामान्य सूचना"),
                            ("important", "महत्वपूर्ण सूचना"),
                            ("event", "कार्यक्रम"),
                            ("other", "अन्य"),
                        ],
                        default="general",
                        help_text="Notice को प्रकार छान्नुहोस्",
                        max_length=20,
                        verbose_name="Notice प्रकार",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Popup मा देखाउने image (JPG, PNG format मा)",
                        upload_to="news_events/popup_notices/",
                        verbose_name="Notice Image",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Image को alt text (accessibility को लागि)",
                        max_length=200,
                        verbose_name="Image Alt Text",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="यदि image click गर्दा कुनै page मा जानुपर्छ भने URL (optional)",
                        verbose_name="Link URL",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Link button को text (optional)",
                        max_length=100,
                        verbose_name="Link Text",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False,
                        help_text="Link नयाँ tab मा खोल्ने हो भने check गर्नुहोस्",
                        verbose_name="नयाँ tab मा खोल्नुहोस्",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority notices appear first. If multiple active notices exist, highest priority shows.",
                        verbose_name="प्राथमिकता",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Check this to show the popup on home page. Uncheck to hide without deleting.",
                        verbose_name="सक्रिय",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="जब देखाउन सुरु गर्ने (default: अहिले)",
                        verbose_name="सुरु मिति",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="जब देखाउन बन्द गर्ने (blank = सधै देखाउने)",
                        null=True,
                        verbose_name="अन्त्य मिति",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
            ],
            options={
                "verbose_name": "Popup Notice",
                "verbose_name_plural": "Popup Notices",
                "ordering": ["-priority", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="news_events_is_acti_af06bc_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_active"],
                        name="news_events_priorit_6a6e62_idx",
                    ),
                    models.Index(
                        fields=["notice_type", "is_active"],
                        name="news_events_notice__ce5d06_idx",
                    ),
                ],
            },
        ),
    ]
