# Generated by Django 5.2.9 on 2026-01-17 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_events", "0004_popupnotice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="सूचनाको शीर्षक", max_length=200, verbose_name="शीर्षक"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-अनुकूल शीर्षक",
                        max_length=250,
                        unique=True,
                        verbose_name="स्लग",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="सूचनाको विस्तृत विवरण", verbose_name="विवरण"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="सूचनाको फाइल (PDF/Image)",
                        null=True,
                        upload_to="news_events/notices/",
                        verbose_name="फाइल",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("GEN", "सामान्य सूचना"),
                            ("URG", "जरुरी सूचना"),
                            ("AGM", "साधारण सभा"),
                            ("TEN", "बोलपत्र"),
                            ("OTH", "अन्य"),
                        ],
                        default="GEN",
                        help_text="सूचना प्रकार",
                        max_length=3,
                        verbose_name="प्रकार",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="प्रकाशन मिति"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="सक्रिय छ कि छैन", verbose_name="सक्रिय"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="माथि देखाउनको लागि",
                        verbose_name="टाँसिएको (Pinned)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
            ],
            options={
                "verbose_name": "सूचना",
                "verbose_name_plural": "सूचनाहरू",
                "ordering": ["-is_pinned", "-published_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "published_date"],
                        name="news_events_is_acti_d752b2_idx",
                    ),
                    models.Index(
                        fields=["is_pinned"], name="news_events_is_pinn_31b739_idx"
                    ),
                ],
            },
        ),
    ]
