# Generated by Django 5.2.9 on 2026-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_events", "0005_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="show_as_popup",
            field=models.BooleanField(
                default=False,
                help_text="Home page मा popup modal मा देखाउने हो भने check गर्नुहोस्",
                verbose_name="Popup मा देखाउनुहोस्",
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["show_as_popup", "is_active"],
                name="news_events_show_as_f86d7d_idx",
            ),
        ),
    ]
