# Generated by Django 5.2.9 on 2026-01-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_events", "0006_notice_show_as_popup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="popupnotice",
            name="auto_close_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Popup कति सेकेन्ड पछि आफैँ बन्द हुने (blank = manual close मात्र, e.g., 5 = 5 सेकेन्ड पछि auto-close)",
                null=True,
                verbose_name="Auto-Close Duration (सेकेन्ड)",
            ),
        ),
    ]
