BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB X  _('Django site admin') BBBBBBBB

BBBBB BBBBBBBBB

XXXXXXX
    XXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
        XXXX XXXXX
        XXXXXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXX XX
        XXXXXX XXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
        XXXXXXX XXXX XX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXX XXXX
        XXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXX
        XXXXXX XXXXXX
        XXXXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX XXXXX X
        XXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXX X
        XXXXXX XXXXX
        XXXXXXXX XXXX
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXX
        XXXXXXX XXXXXXXXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX
        XXXXXX XXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX
    XXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXX XXXXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX XXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        
        XXXX XXXXX XXXXXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXX XXXXXXXXXXXXXXX
            
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            BBB BBBBB BB BBBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXXXXXXXXXXXX X XXX XXXXXX
    
    XX XXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXXXXXXXXXXXX
        XXX
    XXX
    
    XX XXXXXX XXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXX
    XXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    XXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
        XXXXXXXXXXXXXXXXXX
    XXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
            XXXXXXXXXXXXXXXXXX
        X
    XXX
    
    XX XXXXXXXXX XXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XX XXXX XXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        
        XX XXXX XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXX X
            XXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXX
            XXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXX
    XXX
    
    XXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXX XXX XXX
        
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXX XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXX
        X
    X
    
    XX XXXX XXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXX XXX XXXX XXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
        X
    XXX
XXX
XXXXXXXXX
BBBBBBBB
