BBBB BBBBBB


XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
            BBB BBBB BB BBBBBBBBBBB
                BB BBBBBBBBBBBB
                    
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                BBBB
                    
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                            
                        XXXX
                        XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXX
                BBBBB
            BBBBB
                
                XXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX
                    XXXX
                    XXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX
            BBBBBB
        XXXXX
    XXXXXX
XXXXXX
