BBBB BBBBBB
XXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXX XXXX XXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XX XXXXXXX XXXX XXXXXXXXXXXXXX
        
        XXXX XXXXXXXX XXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXX XXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXX XXXXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXX XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXX XXXXXXX XXXXXXX XXXXX XXXX XXXXX
    XXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            XX XXXXX
        X
    XX XXXXXX
    
    XX XXXX XXXXXXX XXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXX XXX XXX XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
        X
    XXX
XXX

XX XXXX XXXXXXXX XXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXXXX X
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XX XXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
X

XX XXXX XXXXXXXX XXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXX
    XXX
X

XX XXXX XXXXXXX XXXXXXX
XXXXXXXX XXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
    X
X

XX XXXX XXXXXXX XXXXXXX
XXXXXXXX XXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XX XXXXX
    X
X
XXXXXXXXX
