BB BBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXX
            XXXX
        XXXXX
        BBBBB

        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBB BB B
                XXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX
            BBBB
                 XXXX
                    XX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX
            BBBBB
        BBBBBB

        BB BBBBBBBBBBBBBBBBB
        XXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXX
            XXXX
        XXXXX
        BBBBB
    XXXXX
XXXXXX
BBBBB
