BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB XXXXX X XXXXXXXXX XXXXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFF FFFFFF FFFF FFFFFFFFFFFFFFFFFFFF FFFFF FF FFFFFFFFF FFFFFFFFFFF FFFFFFFFFBBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXX XXXXXXXX X XXXXXXX XXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XX XXXXXXXXXXXXXX XXXXXX XX
XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXX
    XXXXXXXX XXXX
    XXXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX
X

XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
    XXXXXXX XXXX XX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    XXXXXXX XXXXXXXX
    XXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXXX XXX XXXX XXXXXX
    XXXXXXXX XX
    XXXXXXXXXXX XXXXXXX XXXX XXXXX
    XXXXXXXX XX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XX
X

XXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
X


XX XXXXXXXX XXXXX XXXX XX
XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
    XXXXXXX XXXX XX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    XXXXXXX XXXXXXXX
    XXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
X

XXXXXXXXXXX XXX X
    XXXXXX XXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXX XXX X
    XXXXXXXXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXXX XXX XXXX XXXXXX
    XXXXXXXX XX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXX XX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXX XXXX
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXXXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXX
X

XX XXXXX XXXXX XX
XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXX
    XXXXXXX X XXXXX
X

XX XXXXXXXXXX XXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
    X
X

XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXX
    X
X
XXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXX XXXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                
            XXXXX
            BB BBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX
                    
                XXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXX XXXX XXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXX XXXXXXXXXX XX XXXX XXXXXXXXXXXXXX
        XXXXXX
        
        
        XXXX XXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXX XXX
BB BBBBBBBBBB
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBBBBB BB BBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFFFXXXX
                    BBBBB
                XXXXXX
            XXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB

XXXX XXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXX XXXXXX XX XXXX XXXXXXXXX
        XXXXXX
        
        BB BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX
                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFXXXXXX
                        BBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXX XXXXXXX XXXX XXX XXXXXX XXXX XXXXX XXXX XXXXX XX XXXXXXX XXXXX XXXXXXX
                XXXX
            XXXXXX
        BBBBB
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX
        
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
        
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXX XXXXXX XXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X X
        BBB BBBBB BB BBBBBB
        X
            XXX XXXXXXXXXXXX XX XX
            XXXX XFFFFFFFFXX
            XXXX XFFFFFFFFXX
            XXXXXXXX XFFFFFFFFXX
            XXXXXX XFFFFFFFFXX
            XXXXXXXXX XFFFFFFFFXX
            XXXXXX XXXXXXXXXXXX XX XX
            XXXXXXXXXX XFFFFFFFFXX
            XXXXXXXXXXX FFFFFFFFFFFFFFFFFF
        XBB BBB BBBBBBBBBBBBXBBBBB
        BBBBBB
    XX
    
    XXX XXXXXXXXXXXXXXXXX X XX
    XXX XXXXXXXXXXXXXX X XXXXX
    XXX XXXXXXXXXXXXXXX X XXXXX
    
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXX XXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX X XXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXXX X XXXXXXXXXX
        
        XXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XX XXX XXXXXXXXXXX XXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
    XX
    
    XX XXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
    
    XX XXXXXXXX XXXXX
    XXXXXXXX XXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXX X XX X
            XXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XX
        X
        XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXX XXXXX
    XXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XX X
            XXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXX X XX
        X
        XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXX XXXXXXXX XXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXXX X XXXXXXXXXX
        
        XXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XX XXX XXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    
    XX XXXXX XXXXXXX XX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXX XXX XXXXXXXXX X
            XXXXXXXXXXXXXXXX
        X
    XXX
    
    XX XXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX X
                XXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXX
            X
        X
    XXX
    
    XX XXXXX XXXXXXXX
    XXX XXXXXX X XX
    XXX XXXXXX X XX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXX XXXXXX X XXXX X XXXXXXX
        XXXXX XXXXXX X XXXX X XXXXXXX
        
        XX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X XXX X
            XX XXXXXXX X XX X
                XXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXX
            X
        X
        
        XX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X XXXX X
            XX XXXXXXX X XX X
                XXXXXXXXXXXXXXXX
            X
        X
    XXX
    
    XX XXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXX XXXXXXX
                XXXXX XXXXXX XXX XXXX XXXXX XXXX XXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
            XXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXX XXXXXXXXXXX
        X
    XX
    
    XX XXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
    XX
    
    XX XXXXXX XXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X
        XX XXXX XXXXX XXXXXXXXX XXXX XX XXX XXXX XX XXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXX
    XX
    
    XX XXXX XXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXX
        XX XXXXXX
    X
    
    XX XXX XXX XXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXXXXXX X
            XXXXXXXXX XXXXXX
            XXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
            XXXXXXXX XXXX XXXXXXX
            XXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX
BBBBBBBB BBBBBBBB