BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXX XXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX
        XXXXXXXXXX XXXXXX
        XXXXXXX X XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXX XX
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXX X XXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
        XXXXXXXXXXXXXXXXXXX XXX XXXX
        XXXX XXXX
        XXXXXX XXXXX
        XXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXXXX XXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXX XX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXX XXXXXXXX
    X
    
    XXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXX XX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX XX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX XX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXX XXXXX XX XXXXXXXX 
            XXXXXXXX XXXXXXX XXX XXXXXXXXX XXXXXXXXX
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                XXXXXXXX XXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXX XXXXXX
            XXXX
        XXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX 
                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XX XXX XXXXX XXXXXXXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXXXXXX

XXXX XXX XXXXXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                XXXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXX XXX XXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
            XXXX
        XXXXXX
        
        BB BBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXX 
                                 XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                    BBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXXX XXXXXX XXXXXXX
                    XXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX
                            BBB BBB BB BBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXX
                    XXXXXX
                    BBBBB
                    
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                        XXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX 
                           XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXX X
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBBB
            BBBBBB
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XX XXX XXXXX XXXXXXXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXXXXXX

XXXX XXXXX XXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XX XXXXXXXX XXXX XXXXXX XX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XX XXXXXXXX 
            XXXXXXXX XXXXXXX XXX XXXXXXXXX XXXXXXXXXX
        XXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXX XXXXXX XXXXX XX XXXXXXXXXXXX XXXX 
                    XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXX XXXXX
                XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXX XX XXXXXX XXXX XX XXXXXXX XXXXXXXX XXXXXXXXX 
                    XXXXXXXXXXXX XXX XXXXX XXXX XXXXXXXXXXXX
                XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXX XXXXXXXXX XXXX XX XXXXXX XX XXXXXX XXXXXXXXXXX 
                    XXXXX XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXX XXXXXX XXX XXXXXX 
                    XXXXXXXX XXXX XXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX X XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
    
    XX XXXX XXXXXXX XXXXX
    XXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X XXXXX
    
    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XX
    XX
    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XX X
        XX XXXXXXXXXXXXXX X
            XX XXXX XXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            
            XX XXXXXX XXX XXXXX XXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXX
            X
            
            XX XXXXX XXXXXX XXXXX X XXXXXXX
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXXX
            XX XXXXXX
        X XXXX X
            XXXXX XXX XXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXX
        X
    XX
    XXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXX
        XX XXXXXX
    XXX
X

XX XXXXXXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXX XXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XXXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB
