BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXX XXXXXXX X XXXXXXXXX XXXXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBXXXXXXXXXX XXX XXXXXXX XX XXXXXXX XXXXXXX XXXX XXXXXXXXX XXXX XXXXX XXXXXXXBBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
    XX XX XXXXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XXXXXX
        XXXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXX
        XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXX
    X
    
    XXXXXXXXXX XXXXXXXX X
        XXXX X XXXXXXXX XX X
        XX X XXXXXXXX XX X
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXX XXXX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXX
        XXXXX XXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXX
        XXXX XXXXX
        XXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXXX
        XXXXX XXXXX
        XXXXXXXXXXX XXXXXXX XX XX XXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXX XXXXXX
    X
    
    XXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXXX
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XX XX XXXXX
        XXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXX XXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXX XX XXXXXX XXXXXXXXX
        XXXXXXX X XXXX XXXXX
    X
    
    XXXXXXXXXX XXXXXX X
        XX X XXXXXXXXXX XXXXXXXXXXXXX X
        XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX X
    X
    
    XX XXXXXX XX XXXXXX XX
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXX X
            XXXXXXX XXXXX
            XXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXX
        X
        
        XXXXXXXX X
            XXXX XXXXX
            XXXXX XXXXX
            XXXXXXXX XXXXXXX XXXXX
            XXXXXXXXXX XXXXXX
        X
        
        XXXXXXXX X
            XXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXX XXXXXXXX
        X
    X
    
    XX XXXXXXXXX XXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXX XXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXX
        XXXXXXXX XX
        XXXXXXXXXXX XXXXXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXX XXXX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XX XXXXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXX XXXXXXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
        
        XXXX XXXX XXXXXX XXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
XXXXXX

XXXX XX XXXXXXX XXXXXX XXX
XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXX XX XXXXXXX
    XXXXXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXX XXXXXXXXX X
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XX
        XXXXXXXXXXX X XXX
        XXXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXX X X XXXXXX XX XXXXX XX XXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
        
        XXXXXXXXXXXX
    X
    
    XXXXXX X
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXX X
        XX XXXX XXXXXX XXXX XXXXXX XXXXXXX
        XXXXXXXXXXX X X
            BBB BBBBB BB BBBBBBBBBBBBBB
            X
                XXX X
                XXXX XXX
                XXXXXX XFFFFFFFFXX
                XXXXXXXXXXXX XFFFFFFFFXX
                XXXXXXXXX XXX
                XXXXXX XBB BBBBBBBBBBBFFFFFFFFBBBBXX XXXXXBBBBBX
            XBB BBB BBBBBBBBBBBBXBBBBB
            BBBBBB
        XX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XX XXXXX XX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXX
        XXX
        
        XX XXXX XX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXX
        XXX
        
        XX XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXX
        XXX
        
        XX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XX XXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XX XXXXXXXXXXXXXXXX XXXXXXX
            
            XXXXXXXXXXXXX X
                XXXX XXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX X XX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX XXXX
                XXXX XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
            X
        XXX
        
        XX XXXXXXXXXXX XXXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXX X XXXXXX
        XXX XXXXXXXXXX X XX
        XXX XXXXXXXXXX X XX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XXXXXXXXXXX X XXXXX
            XXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXX X XXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX
            
            XXXXX XXXXXX X XXXXXXXXX X XXXXXXXXXXX
            XXXXX XXXXXX X XXXXXXXXX X XXXXXXXXXXX
            
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            
            XXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXX X XXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXX X XXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXX X XXXXXX
        XXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XX
        XXX XXXXXXXXXX X XX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX X XXXXXXXXXXXXX
            XXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXX X XXXXXXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXX
            
            XXXXX XXXXX X XXXXXXXXXXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXX
            
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            
            XXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXX X XXXXXXXXXXXXXX
        XXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XX 
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
        X
    X
    
    XXXXX XXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXX XXX XX X
            XXXXXXXXX XXXXXX XXXXXXXXX XXX XX XXXXXXXXXX
            XXXXXXX
        X
        
        XX XXXXXXX XXXXXXXXX XXXXXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX X
                XXXXX XXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXX XXX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
                X
            X XXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX
            X
        X
        
        XXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
        
        XX XXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        
        XX XXXX XXXXX XXXXX
        XXXXX XXXXXXXXXXXXXXXXXX
        
        XX XXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        
        XX XXXXX XXXXXXXXX XX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XX XXXX XXXXXXXX XXXXXXX XXXXXX
        X
    X
    
    XXXXXXXX X
        XXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        
        XX XXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXX XXXXXX
        X
    X
    
    XXXXX XXXXXXXXXXXXXXXX X
        XX XXXXXX X X XX XXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXX XXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        
        XX XXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXX X X X XX
        XXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXX
        X
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXX
        XX XXXXXX XX XXXXXX XXXXX XXXXX X XXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXX
        X
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXX XXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
        XXX XXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
        
        XX XXXXXX XXXXXXXX
        XXXXXXX XX XXXXXX X XXXX
        XXXXXXX XX XXXXXX X XXXX
        
        XX XXXXX XXXXXXXX
        XXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXX XXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXX
        XX
        
        XX XXXXXX XXXXXXXXX XXXXXXXXX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX X X XXXXXXXXXXXX X XXX X XXX X XXXX XX XXXXXXX XX XXXXXXXXXX
        XXXXX X X XXXXXXXXXXX X XXX X XXX X XXXX
        
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXX XXX X XXXXXXXX
        
        XX XXXXXX XXXXX XXXXX XX XXXXXX XXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXX X XXXX
        XXXXX XXXXXXX X XXXXXXXXXX X XXXX
        
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXX XXXXXXXXXXXXX XXXXX
            XXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X
X

XX XXXXXXXXXX XX XXXXXXX XXXX XXX XX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXX
XXX
XXXXXXXXX
BBBBBBBB
