# Generated by Django 5.2.7 on 2025-10-21 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('services', '0001_initial'), ('services', '0002_memberrelief_alter_loantype_options_and_more'), ('services', '0003_savingsaccount_services_sa_is_acti_ccf29d_idx_and_more'), ('services', '0004_servicerecommendation_serviceanalytics_and_more'), ('services', '0005_delete_servicecategory_alter_fixeddeposit_options_and_more')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.JSONField(default=dict, verbose_name='User Profile')),
                ('recommended_services', models.JSONField(default=list, verbose_name='Recommended Services')),
                ('recommendation_reason', models.TextField(verbose_name='Recommendation Reason')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Confidence Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Recommendation',
                'verbose_name_plural': 'Service Recommendations',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years')], verbose_name='Duration')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly Payout'), ('quarterly', 'Quarterly Payout'), ('lump_sum', 'Maturity Payout')], max_length=20, verbose_name='Interest Payout')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest Rate (%)')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount (NPR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefits', models.TextField(blank=True, help_text='List key benefits, one per line.', verbose_name='Benefits')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Amount (NPR)')),
            ],
            options={
                'verbose_name': 'Fixed Deposit',
                'verbose_name_plural': 'Fixed Deposits',
                'ordering': ['duration_months', 'interest_rate'],
                'unique_together': {('duration_months', 'payment_frequency')},
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_category', models.CharField(choices=[('business', 'Business Loan'), ('agricultural', 'Agricultural Loan'), ('vehicle', 'Vehicle Loan'), ('foreign_employment', 'Foreign Employment Loan'), ('household', 'Household Loan'), ('house_construction', 'House Construction Loan'), ('land_purchase', 'Land Purchase Loan'), ('education', 'Education Loan'), ('personal', 'Personal Loan')], max_length=30, unique=True, verbose_name='Loan Category')),
                ('nepali_name', models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name')),
                ('english_name', models.CharField(default='Default Name', max_length=100, verbose_name='English Name')),
                ('monthly_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Interest Rate (%)')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Loan Amount (NPR)')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Loan Amount (NPR)')),
                ('max_tenure_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Tenure (Years)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requirements', models.TextField(blank=True, help_text='List required documents, one per line.', verbose_name='Requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefits', models.TextField(blank=True, help_text='List key benefits, one per line.', verbose_name='Benefits')),
                ('color', models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')")),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product')),
                ('slug', models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ['-is_featured', 'english_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberRelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_type', models.CharField(choices=[('medical', 'Medical Relief'), ('education', 'Educational Support'), ('disaster', 'Disaster Relief'), ('welfare', 'Welfare Support')], max_length=20, verbose_name='Relief Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('benefits', models.TextField(verbose_name='Benefits & Support')),
                ('application_process', models.TextField(blank=True, verbose_name='Application Process')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/relief/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')")),
                ('color', models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme')),
                ('is_active', models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('english_name', models.CharField(default='Default Name', max_length=100, verbose_name='English Name')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product')),
                ('nepali_name', models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name')),
                ('slug', models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120)),
            ],
            options={
                'verbose_name': 'Member Relief Program',
                'verbose_name_plural': 'Member Relief Programs',
                'ordering': ['english_name'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('domestic', 'Domestic Transfer'), ('international', 'International Remittance'), ('mobile_banking', 'Mobile Banking Transfer')], max_length=20, verbose_name='Service Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('processing_time', models.CharField(blank=True, help_text="e.g., 'Instant' or '1-2 business days'", max_length=100, verbose_name='Processing Time')),
                ('fees', models.TextField(blank=True, verbose_name='Fees & Charges')),
                ('is_active', models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')")),
                ('color', models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme')),
                ('english_name', models.CharField(default='Default Name', max_length=100, verbose_name='English Name')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product')),
                ('nepali_name', models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name')),
                ('slug', models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120)),
            ],
            options={
                'verbose_name': 'Remittance Service',
                'verbose_name_plural': 'Remittance Services',
                'ordering': ['english_name'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('general', 'General Savings'), ('daily', 'Daily Savings'), ('institutional', 'Institutional Savings'), ('child', 'Child Savings'), ('senior_citizen', 'Senior Citizen Savings'), ('remit', 'Remit Savings'), ('insurance', 'Insurance Savings'), ('monthly', 'Monthly Savings')], max_length=20, unique=True, verbose_name='Account Type')),
                ('nepali_name', models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name')),
                ('english_name', models.CharField(default='Default Name', max_length=100, verbose_name='English Name')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest Rate (%)')),
                ('minimum_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Required minimum balance to maintain.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Balance (NPR)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme')),
                ('features', models.TextField(blank=True, help_text='List key features, one per line.', verbose_name='Key Features')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')")),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product')),
                ('slug', models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
                'ordering': ['-is_featured', '-interest_rate'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='services_sa_is_acti_ccf29d_idx'), models.Index(fields=['interest_rate'], name='services_sa_interes_4c84e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='Applicant Name')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('applicant_address', models.TextField(verbose_name='Address')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Information')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Reviewed By')),
                ('notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Service Type')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Service ID')),
            ],
            options={
                'verbose_name': 'Service Application',
                'verbose_name_plural': 'Service Applications',
                'ordering': ['-applied_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='services_se_content_d7acf7_idx'), models.Index(fields=['status'], name='services_se_status_606402_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('applications_received', models.PositiveIntegerField(default=0)),
                ('calculator_usage', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(verbose_name='Date')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Service Analytics',
                'verbose_name_plural': 'Service Analytics',
                'ordering': ['-date'],
                'unique_together': {('content_type', 'object_id', 'date')},
            },
        ),
    ]
