# Generated by Django 5.2.3 on 2025-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_category', models.CharField(choices=[('business', 'व्यवसाय ऋण (Business Loan)'), ('agricultural', 'कृषि ऋण (Agricultural Loan)'), ('vehicle', 'सवारी खरिद ऋण (Vehicle Purchase Loan)'), ('foreign_employment', 'बैदेशिक रोजगार ऋण (Foreign Employment Loan)'), ('household', 'घरायसि ऋण (Household Loan)'), ('house_construction', 'घर निर्माण ऋण (House Construction Loan)'), ('land_purchase', 'जग्गा खरिद ऋण (Land Purchase Loan)'), ('education', 'शिक्षा ऋण (Education Loan)'), ('personal', 'व्यक्तिगत ऋण (Personal Loan)')], max_length=30, unique=True, verbose_name='Loan Category')),
                ('nepali_name', models.CharField(max_length=100, verbose_name='Nepali Name')),
                ('english_name', models.CharField(max_length=100, verbose_name='English Name')),
                ('monthly_installment_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Monthly Installment Rate (%)')),
                ('quarterly_installment_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Quarterly Installment Rate (%)')),
                ('monthly_interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Monthly Interest Rate (%)')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Loan Amount (NPR)')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Loan Amount (NPR)')),
                ('max_tenure_years', models.IntegerField(blank=True, null=True, verbose_name='Maximum Tenure (Years)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ['loan_category'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('domestic', 'Domestic Transfers'), ('international', 'International Remittance'), ('mobile_banking', 'Mobile Banking')], max_length=20, unique=True, verbose_name='Service Type')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.TextField(blank=True, verbose_name='Features')),
                ('transfer_limit_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Transfer Amount (NPR)')),
                ('transfer_limit_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Transfer Amount (NPR)')),
                ('processing_time', models.CharField(blank=True, max_length=100, verbose_name='Processing Time')),
                ('fees', models.TextField(blank=True, verbose_name='Fees & Charges')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remittance Service',
                'verbose_name_plural': 'Remittance Services',
                'ordering': ['service_type'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('general', 'साधारण बचत (General Savings)'), ('daily', 'दैनिक बचत (Daily Savings)'), ('institutional', 'संस्थागत बचत (Institutional Savings)'), ('child', 'बाल बचत (Child Savings)'), ('senior_citizen', 'जेष्ठ नागरिक बचत (Senior Citizen Savings)'), ('remit', 'रेमिट बचत (Remit Savings)'), ('insurance', 'बिमा बचत (Insurance Savings)'), ('monthly', 'मासिक बचत (Monthly Savings)')], max_length=20, unique=True, verbose_name='Account Type')),
                ('nepali_name', models.CharField(max_length=100, verbose_name='Nepali Name')),
                ('english_name', models.CharField(max_length=100, verbose_name='English Name')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Interest Rate (%)')),
                ('minimum_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Balance (NPR)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
                'ordering': ['interest_rate', 'account_type'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('nepali_name', models.CharField(max_length=100, verbose_name='Nepali Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class (FontAwesome)')),
                ('color', models.CharField(default='deuraligreen', max_length=20, verbose_name='Color Theme')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years')], verbose_name='Duration (Months)')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('lump_sum', 'Lump Sum')], max_length=20, verbose_name='Payment Frequency')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Interest Rate (%)')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Amount (NPR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixed Deposit',
                'verbose_name_plural': 'Fixed Deposits',
                'ordering': ['duration_months', 'payment_frequency'],
                'unique_together': {('duration_months', 'payment_frequency')},
            },
        ),
    ]
