# Generated by Django 5.2.3 on 2025-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_memberrelief_alter_loantype_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['is_active', 'is_featured'], name='services_sa_is_acti_ccf29d_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['account_type'], name='services_sa_account_ecc95c_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['interest_rate'], name='services_sa_interes_4c84e0_idx'),
        ),
    ]
