# Generated by Django 5.2.7 on 2025-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_savingsaccount_services_sa_is_acti_ccf29d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.JSONField(default=dict, verbose_name='User Profile')),
                ('recommended_services', models.JSONField(default=list, verbose_name='Recommended Services')),
                ('recommendation_reason', models.TextField(verbose_name='Recommendation Reason')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Confidence Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Recommendation',
                'verbose_name_plural': 'Service Recommendations',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=20, verbose_name='Service Type')),
                ('service_id', models.IntegerField(verbose_name='Service ID')),
                ('page_views', models.IntegerField(default=0, verbose_name='Page Views')),
                ('applications_received', models.IntegerField(default=0, verbose_name='Applications Received')),
                ('calculator_usage', models.IntegerField(default=0, verbose_name='Calculator Usage')),
                ('comparison_views', models.IntegerField(default=0, verbose_name='Comparison Views')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Analytics',
                'verbose_name_plural': 'Service Analytics',
                'ordering': ['-date'],
                'unique_together': {('service_type', 'service_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('savings', 'Savings Account'), ('loan', 'Loan Service'), ('fixed_deposit', 'Fixed Deposit'), ('remittance', 'Remittance Service'), ('relief', 'Member Relief')], max_length=20, verbose_name='Service Type')),
                ('service_id', models.IntegerField(verbose_name='Service ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='Applicant Name')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('applicant_phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('applicant_address', models.TextField(verbose_name='Address')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Information')),
                ('application_data', models.JSONField(default=dict, verbose_name='Application Data')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('requires_documents', 'Requires Additional Documents')], default='pending', max_length=20, verbose_name='Status')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='Applied Date')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed Date')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Reviewed By')),
                ('notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Service Application',
                'verbose_name_plural': 'Service Applications',
                'ordering': ['-applied_date'],
                'indexes': [models.Index(fields=['service_type', 'status'], name='services_se_service_c04aa0_idx'), models.Index(fields=['applied_date'], name='services_se_applied_514c0c_idx'), models.Index(fields=['applicant_email'], name='services_se_applica_970023_idx')],
            },
        ),
    ]
