# Generated by Django 5.2.7 on 2025-10-21 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0004_servicerecommendation_serviceanalytics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.AlterModelOptions(
            name='fixeddeposit',
            options={'ordering': ['duration_months', 'interest_rate'], 'verbose_name': 'Fixed Deposit', 'verbose_name_plural': 'Fixed Deposits'},
        ),
        migrations.AlterModelOptions(
            name='loantype',
            options={'ordering': ['-is_featured', 'english_name'], 'verbose_name': 'Loan Type', 'verbose_name_plural': 'Loan Types'},
        ),
        migrations.AlterModelOptions(
            name='memberrelief',
            options={'ordering': ['english_name'], 'verbose_name': 'Member Relief Program', 'verbose_name_plural': 'Member Relief Programs'},
        ),
        migrations.AlterModelOptions(
            name='remittanceservice',
            options={'ordering': ['english_name'], 'verbose_name': 'Remittance Service', 'verbose_name_plural': 'Remittance Services'},
        ),
        migrations.AlterModelOptions(
            name='savingsaccount',
            options={'ordering': ['-is_featured', '-interest_rate'], 'verbose_name': 'Savings Account', 'verbose_name_plural': 'Savings Accounts'},
        ),
        migrations.RemoveIndex(
            model_name='savingsaccount',
            name='services_sa_account_ecc95c_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceapplication',
            name='services_se_service_c04aa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceapplication',
            name='services_se_applied_514c0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceapplication',
            name='services_se_applica_970023_idx',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='monthly_installment_rate',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='quarterly_installment_rate',
        ),
        migrations.RemoveField(
            model_name='memberrelief',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='memberrelief',
            name='nepali_title',
        ),
        migrations.RemoveField(
            model_name='memberrelief',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='memberrelief',
            name='title',
        ),
        migrations.RemoveField(
            model_name='remittanceservice',
            name='features',
        ),
        migrations.RemoveField(
            model_name='remittanceservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='remittanceservice',
            name='transfer_limit_max',
        ),
        migrations.RemoveField(
            model_name='remittanceservice',
            name='transfer_limit_min',
        ),
        migrations.AlterUniqueTogether(
            name='serviceanalytics',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='application_data',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='service_type',
        ),
        migrations.AddField(
            model_name='loantype',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120),
        ),
        migrations.AddField(
            model_name='memberrelief',
            name='english_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='English Name'),
        ),
        migrations.AddField(
            model_name='memberrelief',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product'),
        ),
        migrations.AddField(
            model_name='memberrelief',
            name='nepali_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AddField(
            model_name='memberrelief',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120),
        ),
        migrations.AddField(
            model_name='remittanceservice',
            name='color',
            field=models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme'),
        ),
        migrations.AddField(
            model_name='remittanceservice',
            name='english_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='English Name'),
        ),
        migrations.AddField(
            model_name='remittanceservice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product'),
        ),
        migrations.AddField(
            model_name='remittanceservice',
            name='nepali_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AddField(
            model_name='remittanceservice',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120),
        ),
        migrations.AddField(
            model_name='serviceanalytics',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='serviceanalytics',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Service ID'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='benefits',
            field=models.TextField(blank=True, help_text='List key benefits, one per line.', verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='duration_months',
            field=models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years')], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest Rate (%)'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='payment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly Payout'), ('quarterly', 'Quarterly Payout'), ('lump_sum', 'Maturity Payout')], max_length=20, verbose_name='Interest Payout'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='benefits',
            field=models.TextField(blank=True, help_text='List key benefits, one per line.', verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='color',
            field=models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='english_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')"),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='loan_category',
            field=models.CharField(choices=[('business', 'Business Loan'), ('agricultural', 'Agricultural Loan'), ('vehicle', 'Vehicle Loan'), ('foreign_employment', 'Foreign Employment Loan'), ('household', 'Household Loan'), ('house_construction', 'House Construction Loan'), ('land_purchase', 'Land Purchase Loan'), ('education', 'Education Loan'), ('personal', 'Personal Loan')], max_length=30, unique=True, verbose_name='Loan Category'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='max_tenure_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Tenure (Years)'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Loan Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Loan Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='monthly_interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Interest Rate (%)'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='nepali_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='requirements',
            field=models.TextField(blank=True, help_text='List required documents, one per line.', verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='color',
            field=models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')"),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/relief/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='relief_type',
            field=models.CharField(choices=[('medical', 'Medical Relief'), ('education', 'Educational Support'), ('disaster', 'Disaster Relief'), ('welfare', 'Welfare Support')], max_length=20, verbose_name='Relief Type'),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')"),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='processing_time',
            field=models.CharField(blank=True, help_text="e.g., 'Instant' or '1-2 business days'", max_length=100, verbose_name='Processing Time'),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='service_type',
            field=models.CharField(choices=[('domestic', 'Domestic Transfer'), ('international', 'International Remittance'), ('mobile_banking', 'Mobile Banking Transfer')], max_length=20, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='account_type',
            field=models.CharField(choices=[('general', 'General Savings'), ('daily', 'Daily Savings'), ('institutional', 'Institutional Savings'), ('child', 'Child Savings'), ('senior_citizen', 'Senior Citizen Savings'), ('remit', 'Remit Savings'), ('insurance', 'Insurance Savings'), ('monthly', 'Monthly Savings')], max_length=20, unique=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='color',
            field=models.CharField(default='deuraligreen', help_text='Tailwind CSS color name for branding.', max_length=20, verbose_name='Color Theme'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='english_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='features',
            field=models.TextField(blank=True, help_text='List key features, one per line.', verbose_name='Key Features'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')"),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual interest rate.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest Rate (%)'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active services are visible to users.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products appear prominently on the site.', verbose_name='Featured Product'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required minimum balance to maintain.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='nepali_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='applications_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='calculator_usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='applicant_phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='serviceapplication',
            index=models.Index(fields=['content_type', 'object_id'], name='services_se_content_d7acf7_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceapplication',
            index=models.Index(fields=['status'], name='services_se_status_606402_idx'),
        ),
        migrations.RemoveField(
            model_name='serviceanalytics',
            name='comparison_views',
        ),
        migrations.RemoveField(
            model_name='serviceanalytics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serviceanalytics',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='serviceanalytics',
            name='service_type',
        ),
        migrations.AlterUniqueTogether(
            name='serviceanalytics',
            unique_together={('content_type', 'object_id', 'date')},
        ),
    ]
