# Generated by Django 5.2.7 on 2025-10-22 07:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0001_squashed_0005_delete_servicecategory_alter_fixeddeposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='nepali_name',
            field=models.CharField(max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='nepali_name',
            field=models.CharField(max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AlterField(
            model_name='memberrelief',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='nepali_name',
            field=models.CharField(max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AlterField(
            model_name='remittanceservice',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='nepali_name',
            field=models.CharField(max_length=100, verbose_name='Nepali Name'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly identifier. Auto-generated if left blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Service ID'),
        ),
    ]
