# Generated by Django 5.2.9 on 2025-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_fixeddeposit_minimum_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['is_active', 'duration_months'], name='services_fi_is_acti_bc36fe_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['interest_rate'], name='services_fi_interes_a81756_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['created_at'], name='services_fi_created_1b1e05_idx'),
        ),
        migrations.AddIndex(
            model_name='loantype',
            index=models.Index(fields=['is_active', 'is_featured'], name='services_lo_is_acti_018c22_idx'),
        ),
        migrations.AddIndex(
            model_name='loantype',
            index=models.Index(fields=['loan_category', 'is_active'], name='services_lo_loan_ca_6396a4_idx'),
        ),
        migrations.AddIndex(
            model_name='loantype',
            index=models.Index(fields=['monthly_interest_rate'], name='services_lo_monthly_5e613b_idx'),
        ),
        migrations.AddIndex(
            model_name='loantype',
            index=models.Index(fields=['slug'], name='services_lo_slug_925fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='memberrelief',
            index=models.Index(fields=['is_active', 'is_featured'], name='services_me_is_acti_3d0b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberrelief',
            index=models.Index(fields=['relief_type', 'is_active'], name='services_me_relief__032a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberrelief',
            index=models.Index(fields=['slug'], name='services_me_slug_cdbdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceservice',
            index=models.Index(fields=['is_active', 'is_featured'], name='services_re_is_acti_d7fb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceservice',
            index=models.Index(fields=['service_type', 'is_active'], name='services_re_service_684ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceservice',
            index=models.Index(fields=['slug'], name='services_re_slug_77cac0_idx'),
        ),
    ]
