# Generated by Django 5.2.9 on 2025-12-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("services", "0007_fixeddeposit_services_fi_is_acti_bc36fe_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fixeddeposit",
            index=models.Index(
                fields=["payment_frequency", "is_active"],
                name="services_fi_payment_dda1f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixeddeposit",
            index=models.Index(
                fields=["duration_months", "payment_frequency"],
                name="services_fi_duratio_c3388b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixeddeposit",
            index=models.Index(
                fields=["updated_at"], name="services_fi_updated_c7accd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loantype",
            index=models.Index(
                fields=["english_name"], name="services_lo_english_8a74d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loantype",
            index=models.Index(
                fields=["nepali_name"], name="services_lo_nepali__f68b42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loantype",
            index=models.Index(
                fields=["created_at"], name="services_lo_created_0f7715_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loantype",
            index=models.Index(
                fields=["updated_at"], name="services_lo_updated_cee5cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrelief",
            index=models.Index(
                fields=["english_name"], name="services_me_english_329cac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrelief",
            index=models.Index(
                fields=["nepali_name"], name="services_me_nepali__248841_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrelief",
            index=models.Index(
                fields=["created_at"], name="services_me_created_77aeb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrelief",
            index=models.Index(
                fields=["updated_at"], name="services_me_updated_3285c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remittanceservice",
            index=models.Index(
                fields=["english_name"], name="services_re_english_014744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remittanceservice",
            index=models.Index(
                fields=["nepali_name"], name="services_re_nepali__1dc896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remittanceservice",
            index=models.Index(
                fields=["created_at"], name="services_re_created_52c4c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remittanceservice",
            index=models.Index(
                fields=["updated_at"], name="services_re_updated_db7caa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["account_type", "is_active"],
                name="services_sa_account_f83e06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(fields=["slug"], name="services_sa_slug_b2876b_idx"),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["english_name"], name="services_sa_english_20af80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["created_at"], name="services_sa_created_35e533_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["updated_at"], name="services_sa_updated_2a62f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceanalytics",
            index=models.Index(
                fields=["content_type", "object_id", "date"],
                name="services_se_content_d0638c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceanalytics",
            index=models.Index(fields=["date"], name="services_se_date_0c8253_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceanalytics",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="services_se_content_ed936a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceapplication",
            index=models.Index(
                fields=["status", "applied_date"], name="services_se_status_fa43ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceapplication",
            index=models.Index(
                fields=["applied_date"], name="services_se_applied_514c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceapplication",
            index=models.Index(
                fields=["applicant_email"], name="services_se_applica_970023_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceapplication",
            index=models.Index(
                fields=["applicant_phone"], name="services_se_applica_d657c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerecommendation",
            index=models.Index(
                fields=["confidence_score", "created_at"],
                name="services_se_confide_70fc48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerecommendation",
            index=models.Index(
                fields=["created_at"], name="services_se_created_20dc46_idx"
            ),
        ),
    ]
