# Generated by Django 5.2.9 on 2025-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_add_database_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="loantype",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/loans/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="loan_category",
            field=models.CharField(
                choices=[
                    ("business", "Business Loan"),
                    ("agricultural", "Agricultural Loan"),
                    ("vehicle", "Vehicle Loan"),
                    ("foreign_employment", "Foreign Employment Loan"),
                    ("household", "Household Loan"),
                    ("house_construction", "House Construction Loan"),
                    ("home", "Home Loan"),
                    ("land_purchase", "Land Purchase Loan"),
                    ("education", "Education Loan"),
                    ("personal", "Personal Loan"),
                ],
                max_length=30,
                unique=True,
                verbose_name="Loan Category",
            ),
        ),
    ]
