# Generated by Django 5.2.9 on 2025-12-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_add_home_loan_and_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(max_length=100, verbose_name="English Name"),
                ),
                (
                    "nepali_name",
                    models.CharField(max_length=100, verbose_name="Nepali Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="A unique, URL-friendly identifier. Auto-generated if left blank.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="deuraligreen",
                        help_text="Tailwind CSS color name for branding.",
                        max_length=20,
                        verbose_name="Color Theme",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured products appear prominently on the site.",
                        verbose_name="Featured Product",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active services are visible to users.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("mobile_banking", "Mobile Banking"),
                            ("online_banking", "Online Banking"),
                            ("atm_card", "ATM Card"),
                            ("debit_card", "Debit Card"),
                            ("credit_card", "Credit Card"),
                            ("e_wallet", "E-Wallet"),
                            ("qr_payment", "QR Payment"),
                            ("sms_banking", "SMS Banking"),
                        ],
                        max_length=20,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="List key features, one per line.",
                        verbose_name="Key Features",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="List requirements, one per line.",
                        verbose_name="Requirements",
                    ),
                ),
                ("fees", models.TextField(blank=True, verbose_name="Fees & Charges")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/digital/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Service",
                "verbose_name_plural": "Digital Services",
                "ordering": ["english_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="services_di_is_acti_cbf578_idx",
                    ),
                    models.Index(
                        fields=["service_type", "is_active"],
                        name="services_di_service_847562_idx",
                    ),
                    models.Index(fields=["slug"], name="services_di_slug_656dfe_idx"),
                    models.Index(
                        fields=["english_name"], name="services_di_english_067731_idx"
                    ),
                    models.Index(
                        fields=["nepali_name"], name="services_di_nepali__308ca9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="services_di_created_3ef2e9_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="services_di_updated_7d920f_idx"
                    ),
                ],
            },
        ),
    ]
