# Generated by Django 5.2.9 on 2025-12-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_digitalservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsaccount",
            name="category",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Savings (नियमित बचत)"),
                    ("optional", "Optional Savings (एच्छिक बचत)"),
                    ("recurring", "Recurring Savings (क्रमिक बचत)"),
                ],
                default="optional",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("general", "General Savings"),
                    ("daily", "Daily Savings"),
                    ("institutional", "Institutional Savings"),
                    ("child", "Child Savings"),
                    ("senior_citizen", "Senior Citizen Savings"),
                    ("remit", "Remit Savings"),
                    ("insurance", "Insurance Savings"),
                    ("monthly", "Monthly Savings"),
                    ("regular_saving", "Regular Savings"),
                    ("recurring_saving", "Recurring Savings"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Account Type",
            ),
        ),
    ]
