# Generated by Django 5.2.9 on 2025-12-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_add_saving_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixeddeposit",
            name="color",
            field=models.CharField(
                default="deuraligreen",
                help_text="Tailwind CSS color name for branding.",
                max_length=20,
                verbose_name="Color Theme",
            ),
        ),
        migrations.AddField(
            model_name="fixeddeposit",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="fixeddeposit",
            name="english_name",
            field=models.CharField(
                default="Fixed Deposit Scheme",
                max_length=100,
                verbose_name="English Name",
            ),
        ),
        migrations.AddField(
            model_name="fixeddeposit",
            name="icon",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Icon Class (e.g., 'fas fa-piggy-bank')",
            ),
        ),
        migrations.AddField(
            model_name="fixeddeposit",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured products appear prominently on the site.",
                verbose_name="Featured Product",
            ),
        ),
        migrations.AddField(
            model_name="fixeddeposit",
            name="nepali_name",
            field=models.CharField(
                default="मुद्दती निक्षेप", max_length=100, verbose_name="Nepali Name"
            ),
        ),
        migrations.AddField(
            model_name="fixeddeposit",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="fixeddeposit",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only active services are visible to users.",
                verbose_name="Active",
            ),
        ),
    ]
