# Generated by Django 5.2.9 on 2025-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_fixeddeposit_color_fixeddeposit_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixeddeposit",
            name="english_name",
            field=models.CharField(max_length=100, verbose_name="English Name"),
        ),
        migrations.AlterField(
            model_name="fixeddeposit",
            name="nepali_name",
            field=models.CharField(max_length=100, verbose_name="Nepali Name"),
        ),
        migrations.AlterField(
            model_name="fixeddeposit",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="A unique, URL-friendly identifier. Auto-generated if left blank.",
                max_length=120,
                unique=True,
            ),
        ),
    ]
