# Generated by Django 5.2.9 on 2025-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_alter_fixeddeposit_english_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("CHF", "Swiss Franc"),
                            ("CNY", "Chinese Yuan"),
                            ("INR", "Indian Rupee"),
                            ("AED", "UAE Dirham"),
                            ("SAR", "Saudi Riyal"),
                            ("QAR", "Qatari Riyal"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("BHD", "Bahraini Dinar"),
                            ("OMR", "Omani Rial"),
                            ("SGD", "Singapore Dollar"),
                            ("MYR", "Malaysian Ringgit"),
                            ("THB", "Thai Baht"),
                            ("HKD", "Hong Kong Dollar"),
                        ],
                        help_text="ISO 4217 currency code",
                        max_length=3,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "buy_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Rate at which bank buys foreign currency",
                        max_digits=10,
                        verbose_name="Buy Rate (NPR)",
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Rate at which bank sells foreign currency",
                        max_digits=10,
                        verbose_name="Sell Rate (NPR)",
                    ),
                ),
                (
                    "mid_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Average of buy and sell rate",
                        max_digits=10,
                        null=True,
                        verbose_name="Mid Rate (NPR)",
                    ),
                ),
                (
                    "rate_date",
                    models.DateField(
                        help_text="Date for which this rate is valid",
                        verbose_name="Rate Date",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="NRB",
                        help_text="Source of exchange rate (e.g., NRB, Manual)",
                        max_length=50,
                        verbose_name="Source",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active rates are used in calculations",
                        verbose_name="Active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or remarks",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-rate_date", "currency_code"],
                "indexes": [
                    models.Index(
                        fields=["currency_code", "rate_date"],
                        name="services_ex_currenc_eafe4e_idx",
                    ),
                    models.Index(
                        fields=["is_active", "rate_date"],
                        name="services_ex_is_acti_b8af11_idx",
                    ),
                    models.Index(
                        fields=["rate_date"], name="services_ex_rate_da_fd0434_idx"
                    ),
                ],
                "unique_together": {("currency_code", "rate_date")},
            },
        ),
    ]
