# Generated by Django 5.2.9 on 2025-12-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_exchangerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemittanceCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "charge",
                    models.CharField(
                        help_text="e.g., 'US Dollar - 3.99'",
                        max_length=100,
                        verbose_name="Charge",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Currency Code"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="services.remittanceservice",
                        verbose_name="Remittance Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remittance Charge",
                "verbose_name_plural": "Remittance Charges",
                "ordering": ["service", "display_order", "country"],
                "indexes": [
                    models.Index(
                        fields=["service", "display_order"],
                        name="services_re_service_a17508_idx",
                    ),
                    models.Index(
                        fields=["country"], name="services_re_country_0e3c9e_idx"
                    ),
                ],
            },
        ),
    ]
