# Generated by Django 5.2.9 on 2026-01-02 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_add_remittance_charge_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="loantype",
            name="repayment_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly (मासिक)"),
                    ("quarterly", "Quarterly (त्रैमासिक)"),
                    ("seasonal", "Seasonal (मौसमी)"),
                ],
                default="monthly",
                help_text="Frequency of loan repayment. Seasonal is typically used for agricultural loans.",
                max_length=20,
                verbose_name="Repayment Type",
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="monthly_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monthly interest rate. Annual rate = Monthly rate × 12.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Monthly Interest Rate (%)",
            ),
        ),
    ]
