# Generated by Django 5.2.9 on 2026-01-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_loantype_repayment_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanCarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload image for carousel slide. Recommended size: 1920x1080px",
                        upload_to="services/loans/carousel/",
                        verbose_name="Carousel Image",
                    ),
                ),
                (
                    "nepali_tagline",
                    models.CharField(
                        blank=True,
                        help_text="Nepali tagline for this slide",
                        max_length=200,
                        verbose_name="Nepali Tagline",
                    ),
                ),
                (
                    "english_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="English subtitle for this slide",
                        max_length=200,
                        verbose_name="English Subtitle",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this image appears in the carousel (lower numbers appear first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active images are displayed in the carousel",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_images",
                        to="services.loantype",
                        verbose_name="Loan Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Carousel Image",
                "verbose_name_plural": "Loan Carousel Images",
                "ordering": ["loan", "order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["loan", "is_active", "order"],
                        name="services_lo_loan_id_001156_idx",
                    ),
                    models.Index(
                        fields=["loan", "order"], name="services_lo_loan_id_357c86_idx"
                    ),
                ],
            },
        ),
    ]
