# Generated by Django 5.2.9 on 2026-01-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_loancarouselimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="loancarouselimage",
            name="english_tagline",
            field=models.CharField(
                blank=True,
                help_text="Main English tagline for this slide",
                max_length=200,
                verbose_name="English Tagline",
            ),
        ),
        migrations.AddField(
            model_name="loancarouselimage",
            name="nepali_subtitle",
            field=models.CharField(
                blank=True,
                help_text="Nepali subtitle/description for this slide",
                max_length=200,
                verbose_name="Nepali Subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="loancarouselimage",
            name="english_subtitle",
            field=models.CharField(
                blank=True,
                help_text="English subtitle/description for this slide",
                max_length=200,
                verbose_name="English Subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="loancarouselimage",
            name="nepali_tagline",
            field=models.CharField(
                blank=True,
                help_text="Main Nepali tagline for this slide",
                max_length=200,
                verbose_name="Nepali Tagline",
            ),
        ),
    ]
