# Generated by Django 5.2.7 on 2025-10-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='ai_color_palette',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected color palette'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated description'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='ai_objects',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected objects'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='ai_quality_score',
            field=models.FloatField(default=0.0, help_text='AI quality score (0-1)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='ai_scene_type',
            field=models.CharField(blank=True, help_text='AI-detected scene type', max_length=100),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='ai_sentiment',
            field=models.CharField(blank=True, help_text='AI-detected sentiment', max_length=50),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated tags'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Allow comments'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='allow_downloads',
            field=models.BooleanField(default=False, help_text='Allow downloads'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of comments'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Publicly visible'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of shares'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views'),
        ),
        migrations.CreateModel(
            name='GalleryImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.galleryimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImageDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('download_type', models.CharField(choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('medium', 'Medium')], default='original', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='gallery.galleryimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('copy_link', 'Copy Link')], max_length=50)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='gallery.galleryimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.galleryimage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('image', 'user_ip')},
            },
        ),
    ]
