# Generated by Django 5.2.7 on 2025-10-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_ai_color_palette_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='Required AI tags')),
                ('ai_objects', models.JSONField(blank=True, default=list, help_text='Required detected objects')),
                ('ai_scene_type', models.CharField(blank=True, help_text='Required scene type', max_length=100)),
                ('ai_sentiment', models.CharField(blank=True, help_text='Required sentiment', max_length=50)),
                ('ai_color_palette', models.JSONField(blank=True, default=list, help_text='Required color palette')),
                ('min_quality_score', models.FloatField(default=0.0, help_text='Minimum AI quality score')),
                ('is_active', models.BooleanField(default=True, help_text='Active collection')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured collection')),
                ('auto_update', models.BooleanField(default=True, help_text='Automatically update with new images')),
                ('max_images', models.PositiveIntegerField(default=50, help_text='Maximum images in collection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(blank=True, help_text='Last auto-update', null=True)),
            ],
            options={
                'verbose_name': 'Smart Collection',
                'verbose_name_plural': 'Smart Collections',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutoCategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='Required AI tags')),
                ('ai_objects', models.JSONField(blank=True, default=list, help_text='Required detected objects')),
                ('ai_scene_type', models.CharField(blank=True, help_text='Required scene type', max_length=100)),
                ('ai_sentiment', models.CharField(blank=True, help_text='Required sentiment', max_length=50)),
                ('min_quality_score', models.FloatField(default=0.0, help_text='Minimum AI quality score')),
                ('target_category', models.CharField(choices=[('events', 'Events'), ('team', 'Team'), ('office', 'Office'), ('community', 'Community'), ('awards', 'Awards')], help_text='Category to assign', max_length=50)),
                ('mark_featured', models.BooleanField(default=False, help_text='Mark as featured')),
                ('is_active', models.BooleanField(default=True, help_text='Active rule')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Rule priority (higher = more important)')),
                ('auto_apply', models.BooleanField(default=True, help_text='Automatically apply to new images')),
                ('times_applied', models.PositiveIntegerField(default=0, help_text='Number of times this rule was applied')),
                ('last_applied', models.DateTimeField(blank=True, help_text='Last time this rule was applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_album', models.ForeignKey(blank=True, help_text='Album to assign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.galleryalbum')),
            ],
            options={
                'verbose_name': 'Auto Categorization Rule',
                'verbose_name_plural': 'Auto Categorization Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='Raw analysis data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='gallery.galleryimage')),
            ],
            options={
                'verbose_name': 'Image Analysis Job',
                'verbose_name_plural': 'Image Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0, help_text='How well this image matches the collection')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_images', to='gallery.smartcollection')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_collections', to='gallery.galleryimage')),
            ],
            options={
                'ordering': ['-match_score', 'order'],
                'unique_together': {('collection', 'image')},
            },
        ),
    ]
