# Generated by Django 5.2.7 on 2025-10-27 07:02

import django.core.validators
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_smartcollection_autocategorizationrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimagedownload',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='galleryimagelike',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='galleryimageshare',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Album cover image (JPG, PNG, WEBP only)', null=True, upload_to='gallery/albums/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Upload images (JPG, PNG, WEBP only, max 10MB)', upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), gallery.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='autocategorizationrule',
            index=models.Index(fields=['is_active', 'auto_apply', 'priority'], name='gallery_aut_is_acti_d934a5_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['is_active', 'is_featured'], name='gallery_gal_is_acti_800bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['parent_album', 'is_active'], name='gallery_gal_parent__4a3b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['order', 'is_active'], name='gallery_gal_order_f98137_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['created_at'], name='gallery_gal_created_18140c_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_active', 'is_featured'], name='gallery_gal_is_acti_46e81d_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['category', 'is_active'], name='gallery_gal_categor_1e3c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['album', 'is_active'], name='gallery_gal_album_i_924d23_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['created_at'], name='gallery_gal_created_f8dadc_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_public', 'is_active'], name='gallery_gal_is_publ_962ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimagecomment',
            index=models.Index(fields=['image', 'is_approved'], name='gallery_gal_image_i_2deda6_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimagecomment',
            index=models.Index(fields=['created_at'], name='gallery_gal_created_31d04a_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimagedownload',
            index=models.Index(fields=['image', 'created_at'], name='gallery_gal_image_i_75ffeb_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimagedownload',
            index=models.Index(fields=['session_id'], name='gallery_gal_session_098525_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimagelike',
            index=models.Index(fields=['image', 'created_at'], name='gallery_gal_image_i_2b98ca_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimagelike',
            index=models.Index(fields=['session_id'], name='gallery_gal_session_3215f7_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimageshare',
            index=models.Index(fields=['image', 'platform'], name='gallery_gal_image_i_b69936_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimageshare',
            index=models.Index(fields=['created_at'], name='gallery_gal_created_9f7cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcollection',
            index=models.Index(fields=['is_active', 'is_featured'], name='gallery_sma_is_acti_cd4bac_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcollection',
            index=models.Index(fields=['auto_update', 'is_active'], name='gallery_sma_auto_up_dea9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcollectionimage',
            index=models.Index(fields=['collection', 'match_score'], name='gallery_sma_collect_8fdf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcollectionimage',
            index=models.Index(fields=['image', 'collection'], name='gallery_sma_image_i_7fe001_idx'),
        ),
    ]
