# Generated by Django 5.2.7 on 2025-10-27 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryimagedownload_session_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='galleryimagelike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='galleryimagecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryimagedownload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryimagelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryimageshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryimagedownload',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryimagelike',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryimageshare',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='galleryimagelike',
            unique_together={('image', 'session_id')},
        ),
        migrations.AddIndex(
            model_name='galleryimageshare',
            index=models.Index(fields=['session_id'], name='gallery_gal_session_5b5e7a_idx'),
        ),
    ]
