XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX  XXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXX XXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXX 
               XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
               XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXX XXXXX XXX
    BB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX
        XXXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXX XXXXX XXX
    BB BBBBBBBBBBBBB BB BBBBB
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
        XXXXXXX
    XXXXXX
    BBBB BBBBBBBBBBBBB BB BBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX
        XXXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX
                BB BBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                BBBB
                    XX XXXXXXXXXX  XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX   XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXXXXXX
                    XXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFFFXXXX

        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXX 
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXX 
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXX 
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX 
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                BB BBBBBBBBBBBBBBB
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXX 
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXXXXX
                XXXXX
                BBBBB
            XXXXX
            
            BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
                    BBB BBB BB BBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX
           XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXX XXXX
        XXXX
    XXXXXX
XXXXXX
