# Generated by Django 5.2.3 on 2025-06-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., सञ्चालक समिति, लेखा समिति', max_length=150)),
                ('tenure_bs', models.CharField(help_text='e.g., २०८०-२०८३', max_length=20)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name and tenure', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check this for the currently active committees.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (e.g., 1 for Board, 2 for Audit).')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['-is_active', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text=' व्यक्तिको पूरा नाम', max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, help_text=' व्यक्तिको फोटो', null=True, upload_to='person_photos/')),
                ('bio', models.TextField(blank=True, help_text=' व्यक्तिको संक्षिप्त परिचय (optional)')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='e.g., अध्यक्ष, सदस्य, ऋण संयोजक', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the committee (e.g., 1 for President, 2 for VP).')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team.committee')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team.person')),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee', 'order'],
                'unique_together': {('person', 'committee')},
            },
        ),
    ]
