# Generated by Django 5.2.3 on 2025-06-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='e.g., Manager, Accountant', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Date the staff member joined.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the staff member currently employed?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (e.g., 1 for Manager, 2 for others).')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='team.person')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['order'],
            },
        ),
    ]
