# Generated by Django 5.2.7 on 2025-10-21 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('affiliation_type', models.CharField(choices=[('regulatory', 'Regulatory Body'), ('association', 'Professional Association'), ('partnership', 'Partnership'), ('certification', 'Certification Body'), ('other', 'Other')], default='association', max_length=20, verbose_name='Affiliation Type')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/affiliations/', verbose_name='Organization Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Affiliation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affiliation',
                'verbose_name_plural': 'Affiliations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Achievement Title')),
                ('description', models.TextField(verbose_name='Achievement Description')),
                ('achievement_type', models.CharField(choices=[('award', 'Award'), ('certification', 'Certification'), ('recognition', 'Recognition'), ('milestone', 'Milestone'), ('partnership', 'Partnership'), ('other', 'Other')], default='award', max_length=20, verbose_name='Achievement Type')),
                ('received_date', models.DateField(verbose_name='Received Date')),
                ('awarding_organization', models.CharField(max_length=200, verbose_name='Awarding Organization')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='about/achievements/', verbose_name='Certificate Image')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/achievements/', verbose_name='Organization Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Achievement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-received_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_name_nepali', models.CharField(max_length=200, verbose_name='Company Name (Nepali)')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=250, unique=True)),
                ('established_date', models.DateField(verbose_name='Established Date')),
                ('registration_number', models.CharField(max_length=100, verbose_name='Registration Number')),
                ('license_number', models.CharField(max_length=100, verbose_name='License Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('mission', models.TextField(verbose_name='Mission Statement')),
                ('vision', models.TextField(verbose_name='Vision Statement')),
                ('values', models.TextField(verbose_name='Core Values')),
                ('description', models.TextField(verbose_name='Company Description')),
                ('description_nepali', models.TextField(blank=True, verbose_name='Company Description (Nepali)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/company/', verbose_name='Company Logo')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='about/company/', verbose_name='Featured Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Statistic Title')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statistic_type', models.CharField(choices=[('members', 'Total Members'), ('deposits', 'Total Deposits'), ('loans', 'Total Loans Disbursed'), ('branches', 'Number of Branches'), ('employees', 'Number of Employees'), ('assets', 'Total Assets'), ('other', 'Other')], default='other', max_length=20, verbose_name='Statistic Type')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='deuraligreen', max_length=20, verbose_name='Color Theme')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Statistic')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_type', models.CharField(choices=[('milestone', 'Milestone'), ('achievement', 'Achievement'), ('expansion', 'Expansion'), ('award', 'Award'), ('partnership', 'Partnership'), ('other', 'Other')], default='milestone', max_length=20, verbose_name='Event Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/timeline/', verbose_name='Event Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Event')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['event_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Message Title')),
                ('message_type', models.CharField(choices=[('chairman', 'Chairman Message'), ('manager', 'Manager Message'), ('director', 'Director Message'), ('other', 'Other')], default='other', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('author_position', models.CharField(max_length=100, verbose_name='Author Position')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='about/leadership/', verbose_name='Author Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Message',
                'verbose_name_plural': 'Leadership Messages',
                'ordering': ['order', 'message_type'],
            },
        ),
    ]
