# Generated by Django 5.2.7 on 2025-10-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInfo',
            new_name='CooperativeInfo',
        ),
        migrations.RenameModel(
            old_name='CompanyTimeline',
            new_name='CooperativeTimeline',
        ),
        migrations.RenameModel(
            old_name='CompanyAchievement',
            new_name='CooperativeAchievement',
        ),
        migrations.RenameModel(
            old_name='CompanyStatistic',
            new_name='CooperativeStatistic',
        ),
        migrations.RenameModel(
            old_name='CompanyAffiliation',
            new_name='CooperativeAffiliation',
        ),
    ]
