# Generated by Django 5.2.7 on 2025-10-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20251021_1917'),
    ]

    operations = [
        # Rename columns in CooperativeInfo table
        migrations.RenameField(
            model_name='cooperativeinfo',
            old_name='company_name',
            new_name='cooperative_name',
        ),
        migrations.RenameField(
            model_name='cooperativeinfo',
            old_name='company_name_nepali',
            new_name='cooperative_name_nepali',
        ),
    ]
