# Generated by Django 5.2.7 on 2025-10-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20251021_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='व्यक्तिको पूरा नाम', max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='व्यक्तिको फोटो', null=True, upload_to='about/team/photos/')),
                ('bio', models.TextField(blank=True, help_text='व्यक्तिको संक्षिप्त परिचय (optional)')),
                ('email', models.EmailField(blank=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('position_general', models.CharField(blank=True, max_length=100, verbose_name='General Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., सञ्चालक समिति, लेखा समिति', max_length=150)),
                ('tenure_bs', models.CharField(help_text='e.g., २०८०-२०८३', max_length=20)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name and tenure', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check this for the currently active committees.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (e.g., 1 for Board, 2 for Audit).')),
                ('description', models.TextField(blank=True, verbose_name='Committee Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['-is_active', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='e.g., अध्यक्ष, सदस्य, ऋण संयोजक', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the committee (e.g., 1 for President, 2 for VP).')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='about.committee')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='about.person')),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='e.g., Manager, Accountant', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Date the staff member joined.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the staff member currently employed?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (e.g., 1 for Manager, 2 for others).')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('salary_range', models.CharField(blank=True, max_length=50, verbose_name='Salary Range')),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='about.person')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('person', 'committee'), name='about_membership_unique_person_committee'),
        ),
    ]
