# Generated by Django 5.2.7 on 2025-10-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20251021_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperativeinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cooperative Information', 'verbose_name_plural': 'Cooperative Information'},
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='about_membership_unique_person_committee',
        ),
        migrations.AlterField(
            model_name='cooperativeinfo',
            name='cooperative_name',
            field=models.CharField(max_length=200, verbose_name='Cooperative Name'),
        ),
        migrations.AlterField(
            model_name='cooperativeinfo',
            name='cooperative_name_nepali',
            field=models.CharField(max_length=200, verbose_name='Cooperative Name (Nepali)'),
        ),
        migrations.AlterField(
            model_name='cooperativeinfo',
            name='description',
            field=models.TextField(verbose_name='Cooperative Description'),
        ),
        migrations.AlterField(
            model_name='cooperativeinfo',
            name='description_nepali',
            field=models.TextField(blank=True, verbose_name='Cooperative Description (Nepali)'),
        ),
        migrations.AlterField(
            model_name='cooperativeinfo',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/cooperative/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='cooperativeinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='about/cooperative/', verbose_name='Cooperative Logo'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('person', 'committee')},
        ),
    ]
