# Generated by Django 5.2.9 on 2025-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_cooperativeinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperativetimeline',
            options={'ordering': ['-event_date', 'order'], 'verbose_name': 'Timeline Event', 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AddIndex(
            model_name='cooperativeachievement',
            index=models.Index(fields=['is_active', 'is_featured', '-received_date'], name='about_coope_is_acti_956d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperativetimeline',
            index=models.Index(fields=['is_active', 'is_featured', '-event_date'], name='about_coope_is_acti_8750cc_idx'),
        ),
    ]
