# Generated by Django 5.2.9 on 2025-12-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_analyticssummary_usersession_userlocation_userevent_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["slug"], name="about_commi_slug_3e8b4a_idx"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["is_active", "order"], name="about_commi_is_acti_c816e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["name"], name="about_commi_name_cb800a_idx"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["tenure_bs"], name="about_commi_tenure__c1ad65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeachievement",
            index=models.Index(
                fields=["achievement_type", "is_active"],
                name="about_coope_achieve_b32d54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeachievement",
            index=models.Index(
                fields=["received_date"], name="about_coope_receive_1fba10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeachievement",
            index=models.Index(
                fields=["created_at"], name="about_coope_created_e4bf3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeachievement",
            index=models.Index(fields=["title"], name="about_coope_title_74fba5_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="about_coope_is_acti_42ca1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(
                fields=["affiliation_type", "is_active"],
                name="about_coope_affilia_72952b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(fields=["order"], name="about_coope_order_6df786_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(fields=["name"], name="about_coope_name_6c88cc_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(
                fields=["created_at"], name="about_coope_created_357066_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(fields=["slug"], name="about_coope_slug_e84132_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["is_active"], name="about_coope_is_acti_e93a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["created_at"], name="about_coope_created_53be59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["updated_at"], name="about_coope_updated_5d492f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["cooperative_name"], name="about_coope_coopera_c450bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="about_coope_is_acti_31cec4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(
                fields=["statistic_type", "is_active"],
                name="about_coope_statist_2f0f95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(fields=["order"], name="about_coope_order_de9604_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(fields=["title"], name="about_coope_title_2ce19a_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(
                fields=["created_at"], name="about_coope_created_4a0918_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(
                fields=["event_type", "is_active"],
                name="about_coope_event_t_21cbc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(
                fields=["event_date"], name="about_coope_event_d_ab5a10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(
                fields=["created_at"], name="about_coope_created_521bd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(fields=["title"], name="about_coope_title_933379_idx"),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="about_leade_is_acti_9ee994_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(
                fields=["message_type", "is_active"],
                name="about_leade_message_6bf0fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(fields=["order"], name="about_leade_order_34b8a1_idx"),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(fields=["title"], name="about_leade_title_8643da_idx"),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(
                fields=["author_name"], name="about_leade_author__cddaa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(
                fields=["created_at"], name="about_leade_created_d42af1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["committee", "order"], name="about_membe_committ_459269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["person", "committee"], name="about_membe_person__bcf0b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["is_active"], name="about_membe_is_acti_e373d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["position"], name="about_membe_positio_72998e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["full_name"], name="about_perso_full_na_e4eb28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["is_active"], name="about_perso_is_acti_a17b0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="about_perso_email_f9bbb9_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["created_at"], name="about_perso_created_2a6671_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["person"], name="about_staff_person__82c871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["is_active", "order"], name="about_staff_is_acti_873ffa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["position"], name="about_staff_positio_9110c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["department"], name="about_staff_departm_aa9c83_idx"
            ),
        ),
    ]
