# Generated by Django 5.2.9 on 2025-12-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_add_database_indexes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CooperativeAchievement",
        ),
    ]
