# Generated by Django 5.2.9 on 2025-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0009_remove_achievements_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalyticsSummary",
        ),
        migrations.RemoveField(
            model_name="userdevice",
            name="session",
        ),
        migrations.RemoveField(
            model_name="userevent",
            name="session",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="session",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.AlterField(
            model_name="cooperativeaffiliation",
            name="affiliation_type",
            field=models.CharField(
                choices=[
                    ("regulatory", "Regulatory Body"),
                    ("association", "Professional Association"),
                    ("partnership", "Partnership"),
                    ("certification", "Certification Body"),
                    ("umbrella", "Umbrella Organization"),
                    ("other", "Other"),
                ],
                default="association",
                max_length=20,
                verbose_name="Affiliation Type",
            ),
        ),
        migrations.DeleteModel(
            name="PageView",
        ),
        migrations.DeleteModel(
            name="UserDevice",
        ),
        migrations.DeleteModel(
            name="UserEvent",
        ),
        migrations.DeleteModel(
            name="UserLocation",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
