# Generated by Django 5.2.9 on 2025-12-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0010_add_umbrella_organization_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cooperativeaffiliation",
            name="affiliation_type",
            field=models.CharField(
                choices=[
                    ("regulatory", "Regulatory Body"),
                    ("association", "Professional Association"),
                    ("partnership", "Partnership"),
                    ("certification", "Certification Body"),
                    ("umbrella", "Umbrella Organization"),
                    ("cooperative_bank", "Cooperative Bank"),
                    ("other", "Other"),
                ],
                default="association",
                max_length=20,
                verbose_name="Affiliation Type",
            ),
        ),
    ]
