# Generated by Django 5.2.9 on 2025-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0011_add_cooperative_bank_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="position_custom",
            field=models.CharField(
                blank=True,
                help_text="Enter custom position if 'Other' is selected above (e.g., अध्यक्ष, सदस्य, ऋण संयोजक)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order within the committee (e.g., 1 for Chairman, 2 for Vice-Chairman).",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chairman", "Chairman"),
                    ("vice_chairman", "Vice-Chairman"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("member", "Member"),
                    ("coordinator", "Coordinator"),
                    ("other", "Other"),
                ],
                help_text="Select standard position or enter custom position below",
                max_length=100,
            ),
        ),
    ]
