# Generated by Django 5.2.9 on 2025-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0012_add_committee_position_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Group photo or representative image of the committee",
                null=True,
                upload_to="about/committees/",
                verbose_name="Committee Photo",
            ),
        ),
    ]
