# Generated by Django 5.2.9 on 2025-12-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0013_add_committee_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeinfo",
            name="information_officer_designation",
            field=models.CharField(
                blank=True,
                help_text="Official designation/position of the Information Officer",
                max_length=100,
                verbose_name="Information Officer Designation",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="information_officer_email",
            field=models.EmailField(
                blank=True,
                default="rti@bhanjyang.coop.np",
                help_text="RTI email address",
                max_length=254,
                verbose_name="Information Officer Email",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="information_officer_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the designated Information Officer (सूचना अधिकारी)",
                max_length=100,
                verbose_name="Information Officer Name",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="information_officer_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Information Officer Phone"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Position"),
                    ("chairman", "Chairman"),
                    ("vice_chairman", "Vice-Chairman"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("member", "Member"),
                    ("coordinator", "Coordinator"),
                    ("other", "Other"),
                ],
                help_text="Select standard position or enter custom position below",
                max_length=100,
            ),
        ),
    ]
