# Generated by Django 5.2.9 on 2025-12-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0014_add_information_officer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeinfo",
            name="information_officer_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the Information Officer (recommended: 300x300px)",
                null=True,
                upload_to="about/information_officer/",
                verbose_name="Information Officer Photo",
            ),
        ),
    ]
