# Generated by Django 5.2.9 on 2025-12-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0015_add_information_officer_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="information_officer_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Dedicated email for RTI requests (e.g., rti@bhanjyang.coop.np)",
                max_length=254,
                verbose_name="RTI Email",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_information_officer",
            field=models.BooleanField(
                default=False,
                help_text="Designate this staff member as the Information Officer under RTI Act 2064",
                verbose_name="Information Officer (सूचना अधिकारी)",
            ),
        ),
    ]
