# Generated by Django 5.2.9 on 2025-12-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0016_add_information_officer_to_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="information_officer_designation",
        ),
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="information_officer_email",
        ),
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="information_officer_name",
        ),
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="information_officer_phone",
        ),
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="information_officer_photo",
        ),
    ]
