# Generated by Django 5.2.9 on 2025-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0017_remove_cooperative_info_officer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeinfo",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image for the About Us page",
                null=True,
                upload_to="about/cooperative/",
                verbose_name="About Page Hero Image",
            ),
        ),
    ]
