# Generated by Django 5.2.9 on 2025-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0018_cooperativeinfo_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeinfo",
            name="our_story_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the Our Story section on About Us page",
                null=True,
                upload_to="about/cooperative/",
                verbose_name="Our Story Image",
            ),
        ),
    ]
