# Generated by Django 5.2.9 on 2025-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0019_cooperativeinfo_our_story_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="hero_image",
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="our_story",
            field=models.TextField(
                blank=True,
                help_text="Content for the 'Our Story' section on About Us page",
                verbose_name="Our Story",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="our_story_nepali",
            field=models.TextField(
                blank=True,
                help_text="Our Story content in Nepali",
                verbose_name="Our Story (Nepali)",
            ),
        ),
    ]
