# Generated by Django 5.2.9 on 2025-12-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0020_add_our_story_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeinfo",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Location or branch (e.g., Dubai, Kathmandu)",
                max_length=200,
                verbose_name="Location",
            ),
        ),
    ]
