# Generated by Django 5.2.9 on 2025-12-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0021_cooperativeinfo_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cooperativeinfo",
            name="location",
        ),
    ]
