# Generated by Django 5.2.9 on 2025-12-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove orphaned analytics models that were created in migration 0007
    but never implemented in the codebase.
    
    These models (AnalyticsSummary, UserSession, UserLocation, UserEvent, 
    UserDevice, PageView) were created but:
    - analytics.py file doesn't exist
    - Models are not in models.py
    - Models are not registered in admin.py
    - No code references these models
    
    Analytics functionality is available in other apps (dashboard, home).
    """

    dependencies = [
        ("about", "0022_remove_cooperativeinfo_location"),
    ]

    operations = [
        # Delete models in reverse dependency order (children first, then parents)
        migrations.DeleteModel(
            name='UserLocation',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='AnalyticsSummary',
        ),
    ]
