# Generated by Django 5.2.9 on 2025-12-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove orphaned analytics models that were created in migration 0007
    but never implemented in the codebase.
    
    These models (AnalyticsSummary, UserSession, UserLocation, UserEvent, 
    UserDevice, PageView) were created but:
    - analytics.py file doesn't exist
    - Models are not in models.py
    - Models are not registered in admin.py
    - No code references these models
    
    Analytics functionality is available in other apps (dashboard, home).
    """

    dependencies = [
        ("about", "0022_remove_cooperativeinfo_location"),
    ]

    operations = [
        # Note: These models were already deleted in migration 0010_add_umbrella_organization_type.py
        # This migration is kept for documentation purposes but has no operations
        # to avoid duplicate deletion errors.
    ]
