# Generated by Django 5.2.9 on 2026-01-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0023_remove_orphaned_analytics_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeinfo",
            name="introduction_text",
            field=models.TextField(
                blank=True,
                help_text="Text for the introduction section on home page",
                verbose_name="Introduction Text",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="introduction_text_nepali",
            field=models.TextField(
                blank=True,
                help_text="Introduction text in Nepali",
                verbose_name="Introduction Text (Nepali)",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Meta description for SEO and social sharing",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords for SEO",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Page title for SEO (e.g., 'Bhanjyang Cooperative - Home')",
                max_length=200,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for social media sharing (1200x630px recommended)",
                null=True,
                upload_to="about/cooperative/",
                verbose_name="Open Graph Image",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="why_choose_us_text",
            field=models.TextField(
                blank=True,
                help_text="Text for the 'Why Choose Us' section on home page",
                verbose_name="Why Choose Us Text",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="why_choose_us_text_nepali",
            field=models.TextField(
                blank=True,
                help_text="Why Choose Us text in Nepali",
                verbose_name="Why Choose Us Text (Nepali)",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="color",
            field=models.CharField(
                default="deuraligreen",
                help_text="Choose 'deuraligreen' or 'bhanjyangred' for border and icon colors",
                max_length=20,
                verbose_name="Color Theme",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Short description shown below the statistic (e.g., 'Growing our community, one member at a time.')",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="FontAwesome icon class (e.g., 'fas fa-users', 'fas fa-chart-line', 'fas fa-hand-holding-usd', 'fas fa-piggy-bank', 'fas fa-calendar-check')",
                max_length=50,
                verbose_name="Icon Class",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this statistic without deleting it",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Only featured statistics appear in the 'Our Impact' section on the home page. Check this to display on home page.",
                verbose_name="Featured Statistic",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first. Set 0, 1, 2, 3... for ordering on home page",
                verbose_name="Display Order",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="statistic_type",
            field=models.CharField(
                choices=[
                    ("members", "Total Members"),
                    ("deposits", "Total Deposits"),
                    ("loans", "Total Loans Disbursed"),
                    ("branches", "Number of Branches"),
                    ("employees", "Number of Employees"),
                    ("assets", "Total Assets"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Category for organizing statistics",
                max_length=20,
                verbose_name="Statistic Type",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="title",
            field=models.CharField(
                help_text="e.g., 'Active Members', 'Years of Service', 'Total Savings'",
                max_length=200,
                verbose_name="Statistic Title",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Optional unit (e.g., 'members', 'years', 'Million NPR', '%')",
                max_length=50,
                verbose_name="Unit",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativestatistic",
            name="value",
            field=models.CharField(
                help_text="e.g., '10K+', '25+', '500', '98%' (numbers or text)",
                max_length=100,
                verbose_name="Value",
            ),
        ),
    ]
