# Generated by Django 5.2.9 on 2026-01-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0024_cooperativeinfo_introduction_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativeaffiliation",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this affiliation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_affiliations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeaffiliation",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this affiliation was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeaffiliation",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this affiliation to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeaffiliation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_cooperative_info",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this content was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this content to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativeinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="cooperativestatistic",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this statistic",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_about_statistics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="cooperativestatistic",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this statistic was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativestatistic",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this statistic to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativestatistic",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="cooperativetimeline",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_timeline_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="cooperativetimeline",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this event was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativetimeline",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this event to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="cooperativetimeline",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="leadershipmessage",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_leadership_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="leadershipmessage",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this message was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="leadershipmessage",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this message to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="leadershipmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(
                fields=["status", "is_active"], name="aff_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(fields=["status", "order"], name="aff_status_order_idx"),
        ),
        migrations.AddIndex(
            model_name="cooperativeaffiliation",
            index=models.Index(
                fields=["status", "scheduled_date"], name="aff_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["status", "is_active"], name="coop_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["status", "scheduled_date"], name="coop_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativeinfo",
            index=models.Index(
                fields=["status", "published_date"], name="coop_status_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(
                fields=["status", "is_active"], name="about_stat_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(
                fields=["status", "order"], name="about_stat_status_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativestatistic",
            index=models.Index(
                fields=["status", "scheduled_date"], name="about_stat_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(
                fields=["status", "is_active"], name="timeline_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(
                fields=["status", "scheduled_date"], name="timeline_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cooperativetimeline",
            index=models.Index(
                fields=["status", "event_date"], name="timeline_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(
                fields=["status", "is_active"], name="msg_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(fields=["status", "order"], name="msg_status_order_idx"),
        ),
        migrations.AddIndex(
            model_name="leadershipmessage",
            index=models.Index(
                fields=["status", "scheduled_date"], name="msg_status_sched_idx"
            ),
        ),
    ]
