# gallery/constants.py
"""
Constants for gallery app configuration.
"""

# Image Processing Constants
MOBILE_IMAGE_SIZE = (800, 600)
MOBILE_IMAGE_QUALITY = 85
THUMBNAIL_SIZE = (300, 200)
THUMBNAIL_QUALITY = 80
THUMBNAIL_SIZE_LARGE = (800, 600)

# Image Size Limits
MAX_IMAGE_SIZE_MB = 10
MAX_IMAGE_SIZE_BYTES = 10 * 1024 * 1024  # 10MB
MAX_IMAGE_DIMENSION = 5000
MIN_IMAGE_DIMENSION = 100
WARN_IMAGE_DIMENSION = 4000

# Pagination Settings
DEFAULT_PAGE_SIZE = 20
ADMIN_LIST_PER_PAGE = 25
SEARCH_RESULT_LIMIT = 20

# String Length Limits
MAX_SESSION_ID_LENGTH = 100
MAX_URL_LENGTH = 500
MAX_TITLE_LENGTH = 200
MAX_USER_AGENT_LENGTH = 500
MAX_IP_LENGTH = 45

# AI Quality Scores
MAX_QUALITY_SCORE = 1.0
MIN_QUALITY_SCORE = 0.0

