BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Events')  X XXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Browse all upcoming and past events from Bhanjyang Saving & Credit Cooperative Society Ltd.') BBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Events')  X XXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u'Browse all upcoming and past events from Bhanjyang Cooperative.') BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBB
XXXX XXXX XX XXXX XXXXXXX XXXX XXX XXXXXXXXXXXXX XXX
XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
     gettext(u'Skip to main content') 
XXXX

XXXX XXXXXX XXXXXXXXXX XXX
BB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Events') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Join us for exciting events and activities') 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXX XXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXXX XXX XXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXX XXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXX 
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                            XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'All Events') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXX
                            XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Upcoming') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXX
                            XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Past Events') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Featured') 
                    XXXXXXXXX
                XXXXXX

                XXXX XXXXXX XXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search events...') X
                                    XXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXX gettext(u'All Types') XXXXXXXXX
                                BBB BBBBBB BBBBB BB BBBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXXX
                                BBBBBB
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX

    XXXX XXXXXX XXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                
                XXXX XXXXXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                    
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXXXXXXX XXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXX
                                XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXX
                                    
                                    XXXX XXXXX XXXXXXX XXX
                                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX
                                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                                XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                        XXXXXXXXXXX
                                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                                            XXXXXX
                                        XXXXXXXXXXX

                                        XXXX XXXXXXXX XXXXX XXX
                                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXX
                                                XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                                                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Featured') 
                                                XXXXXXX
                                            XXXXXX
                                        XXXXXXXXXXX

                                        XXXX XXXXXX XXXXX XXX
                                        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                                            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                                                  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XX XXXXXXXXXXXX XXX XXXXXX
                                                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXXX
                                        XXXXXX
                                    XXXXXX

                                    XXXX XXXXXXX XXXXXXX XXX
                                    XXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXX XXXX XXXXXXXXXX
                                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                                            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                        
                                        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX
                                        
                                        XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXXXXX

                                        XXXX XXXXX XXXXXXX XXX
                                        XXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                                                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                                                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXX
                                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXX
                                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                                                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                                                    XX XXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXX
                                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXX
                                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                                                    XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                                                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXX
                                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXX
                                            XXXXXXXXXXX
                                        XXXXXX

                                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                                                XX XXXXXXXXXX XXXXXX XXXXXXXXXX
                                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXX
                                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                                                     gettext(u'Registration Required') 
                                                XXXXXXX
                                            XXXXXXXXXXX
                                        XXXXXX
                                    XXXXXX
                                XXXXXXXXXX
                            XXXXXXXXXXX
                        XXXXXX
                    XXXXXXXXXXX

                    XXXX XXXXX XXXXX XXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
                                XXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'No Events Found') XXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u"We couldn't find any events matching your criteria.") XXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXX gettext(u'Clear Filters') XXXXXXX
                                XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXXXXXX

                    XXXX XXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX 
                                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX

                            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX

                            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                                    XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Newsletter') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Stay Updated') 
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Subscribe to our newsletter for the latest events and updates.') 
        XXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter your email') X XXXXXXXX
                    XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXXXX gettext(u'Subscribe') XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X
XXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXX XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXXXXXXX XX XX XX
            XXXXXXX XXX
            XXXXXXXX XXXXX
            XXXXXXX XFFFFFFFFFFXX
            XXXXX XFFFFFFFFFFXX
            XXXXXXX XFFFFFFFFFFXX
            XXXXXXXXX FFFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXX XX
            XXXXXXXXX XX
            XXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX

            XXXXXX X
                XXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX XX XX X XXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXX XXX
                XXXXXXXXXXXXXXXXXXX XX XX X XXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXX XXX
                XX XXXXXX XXX XXXXXXXX XXX XXXXXXX XX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX
            XX

            XXXXX XXXXXXXXXXXXX X
                XXXXXXXXXXXX X XXXXX
                XXX X
                    XXXXX XXXXXX X X
                        XXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXX
                        XXXXX XXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXX
                    XX
                    
                    XX XXXXXX XXX XXXXX XXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXX XX XX XXXXXXXXXXX XXX XXXXXX XX XXXXXX XXXXXXXXXXXXX

                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                    XXXXXXXXXXXX X XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                    
                    XX XXXXXX XXX XXXXXXX XXXXXX
                    XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX

                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX
                X XXXXXXX X
                    XXXXXXXXXXXX X XXXXXX
                X
            XX

            XXXXXXXXXX X
                XX XXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXX XXXXXXXX XXX
                X
            XX

            XXXXXXXXXX X
                XX XXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXX XXXXXXXX XXX
                X
            XX

            XXXXXXXXXXXXXX X
                XXXXXXXXXXX X XXX
                XXXXXXXXX X XXX
                XXXXXXXXXXX X XXX
                XXXXXXXXXXXXX X XXXXXX
                XXXXXXXXXXXXXXXX X XX
                XXXXXXXXXXXXXXXXXXX
            XX

            XXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXX X XXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XXXXXX XXXXXXX XXXX XXXXXXXXX XXX
            XX

            XXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXX X XXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXX
            X
        XXXX
    XXX
XXXXXXXXX
BBBBBBBB BBBBBBBB
