BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'News & Events')  X XXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Stay updated with the latest news, events, and announcements from Bhanjyang Saving & Credit Cooperative Society Ltd.') BBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'News & Events')  X XXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u'Stay updated with the latest news, events, and announcements from Bhanjyang Cooperative.') BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXXXXXXX XXXXX XXX XXXXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXX gettext(u'Skip links') X XXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Skip to main content') 
    XXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Skip to latest news') 
    XXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Skip to upcoming events') 
    XXXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Skip to newsletter') 
    XXXX
XXXXXX

XXXX XXXXXX XXXXXXXXXX XXX
BB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX gettext(u'News and Events Hero') X XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'News & Events') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Stay connected with the latest happenings from Bhanjyang Cooperative') 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXXX XXXXXXX XXX
BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Featured') 
            XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                 gettext(u'Featured Content') 
            XXXXX
            XXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXX XXXXXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                         gettext(u'Featured Articles') 
                    XXXXX
                XXXXXX
                
                XXXX XXXX XXXX XXX
                XXXX XXXXXXXXXX XXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXX
                                XXXX XXXXXXX XXXXX XXX
                                BB BBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX
                                BBBB
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX
                                BBBBB
                                
                                XXXX XXXXXXX XXXXXXX XXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                                        
                                    XXXXX
                                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
                                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XXXXXXFFFFFFFFFFFFFXXXXXXX
                                        XXXXXXX
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XXXXXX  gettext(u'min') XXXXXXX
                                        XXXXXXX
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XXXXXXXXXXXXX
                                        XXXXXXX
                                    XXXXXX
                                XXXXXX
                                
                                XXXX XXXXX XXXX XXX
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB

            XXXX XXXXXXXX XXXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                         gettext(u'Featured Events') 
                    XXXXX
                XXXXXX
                
                XXXX XXXX XXXX XXX
                XXXX XXXXXXXXXX XXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXX
                                XXXX XXXXX XXXXX XXX
                                BB BBBBBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX
                                BBBB
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX
                                BBBBB
                                
                                XXXX XXXXX XXXXXXX XXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                                        
                                    XXXXX
                                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
                                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XXXXXXFFFFFFFFFFFFFXXXXXXX
                                        XXXXXXX
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XXXXXXXXXXXXX
                                        XXXXXXX
                                        BB BBBBBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XXXXXXXXXXXXX
                                        XXXXXXX
                                        BBBBB
                                    XXXXXX
                                XXXXXX
                                
                                XXXX XXXXX XXXX XXX
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB

XXXX XXXXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                     gettext(u'Latest News') 
                XXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX gettext(u'View All Articles') XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Loading articles') XX
            BBB B BB BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBB BB BBBBBBBBBBBBBBB
            XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXX XXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFXX
                XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
                BB BBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                BBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
                XXXX XXXX XXXXXXXXXX XXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXX XXXXXXXXXXXXXXX XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFFFX
                        XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXX
                XXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
                        XXXXXXFFFFFFFFFFFFFXXXXXXX
                        XX XXXXXXX
                            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFXXXX
                    XXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                            XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'No Articles Yet') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Check back soon for the latest news and updates.') XXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                     gettext(u'Upcoming Events') 
                XXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX gettext(u'View All Events') XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Loading events') XX
            BBB B BB BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                        XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX XXXXXXXX XXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFXX
                BB BBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
                XXXX XXXX XXXXXXXXXX XXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
                            
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFF FFFXXXXXXX
                    XXXXXX

                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                        XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX

                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX

                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                        XXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                            XXXXXXFFFFFFFFFFFFFXXXXXXX
                            BB BBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXFFFFFFFFFFFFFXXXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXX XXXXXXXXXX
                            XXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX

                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                        XX XXXXXXFFFFFFFFFFFX
                            XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXX gettext(u'Register Now') XXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'No Upcoming Events') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Check back soon for upcoming events and activities.') XXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Newsletter Subscription') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Newsletter') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Stay Updated') 
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             gettext(u'Subscribe to our newsletter and never miss important updates, news, and events from Bhanjyang Cooperative.') 
        XXXX

        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX gettext(u'Newsletter subscription form') XX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            
            XXXX XXXXXXXX XXXXX XXX XXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX 
                    XXXXXXXXXXXXX gettext(u'Enter your email address') X 
                    XXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX gettext(u'Email address') X
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXXXX gettext(u'Subscribe') XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'We respect your privacy and never share your email address.') XXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Our Impact') 
            XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXBBBBB
                XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Published Articles') XXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXBBBBB
                XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Upcoming Events') XXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXBBBBB
                XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Total Views') XXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Community Access') XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
XX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX X X
    XXXXXXXXXXX X gettext(u'Please enter your email address.') XX
    XXXXXXXXXXXX X gettext(u'Subscribing...') XX
    XXXXXXXXXXXXXXXXXXX X gettext(u'Subscription failed. Please try again later.') X
XX

XX XXXXXXXX XXXXXXXXX XXXXXXXX
XXXXXXXXXXX X
    XXXX XXXXXXXX
    
    XX XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXX XXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXX
            X
            
            XX XXXXX XXXXXXXXX
            XX XXXXXXX XXXX XXX XXXXXXXXXXXX X
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX X
                XXX
            X
        XXX
    X
    
    XX XXXXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXX XXXX XXX XXXXXXXXXXX XX XXXXXXXXXXXXX X
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXX X
                XXX
            X
        XXX
    XXX
    
    XX XXXXX XXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXX XXXX XXX XXXXXXXXXXX XX XXXXXXXXXXX X
                XXXXXXXXXXXXX XXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXX X
                XXX
            X
        XXX
    XXX
    
    XX XXXXX XXXXXX XXXXX
    XXX XXXXXXXXXXX X XX
    XXX XXXXXXXXXXX X XXXXX
    
    XXXXX XXXXXXXXXXXXXXXX X XX XX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXX
        
        XX XXXXXXXX X XXXXXXXXXXX XX XXXXXXX X XX XXX XX X
            XXXXXXXXXXX X XXXXXXXX
            XX XXXXXXX XXXX XXX XXXXXXXXXXXX X
                XXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXX X XXXX
                    XXXXXXXX XXXXXXX
                XXX
            X
        X
    XX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XX XXXXXXXX XXXXXX XXXXXXXX
        XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XX X XXXXXXXX XXXX XXX
    
    XX XXXXX XXXX XX XXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXX
        XX XXXXXXX XXXX XXX XXXXXXXXXXX XX XXXXXXXXXX X XX X
            XXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX
            XXX
        X
    XXX
XXXXX
XXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXX
XXXXXXXX
XX XXXXXXXXXXXXXXXX XX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXX XX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
    XXX
X
XXXXXXXXX

XXXX XXXXXXXXXX XXXX XXXXXXXXX XXX XXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXX
    XXXXXXX X gettext(u'News & Events')  X XXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX X gettext(u'Stay updated with the latest news, events, and announcements from Bhanjyang Saving & Credit Cooperative Society Ltd.') XX
    XXXXXX XXX
    XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
    XX
    XXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXXX
        XXXXXXX X
            XXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX
        X
    XX
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X
            X
                XXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXX XX
                XXXXXXX X gettext(u'Latest News') XX
                XXXXXX XXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
            XX
            X
                XXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXX XX
                XXXXXXX X gettext(u'Upcoming Events') XX
                XXXXXX XXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
            X
        X
    X
X
XXXXXXXXX
BBBBBBBB BBBBBBBB
