BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Search')  X XXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Search through news articles and events from Bhanjyang Cooperative.') BBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Search')  X XXXXXXXX XXXXXXBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBB gettext(u'Search through news articles and events from Bhanjyang Cooperative.') BBBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXX XX XXXX XXXXXXX XXXX XXX XXXXXXXXXXXXX XXX
XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
     gettext(u'Skip to main content') 
XXXX

XXXX XXXXXX XXXXXXXXXX XXX
BB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

XXXX XXXXXX XXXXXXX XXX
XXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX gettext(u'Find articles and events that interest you.') XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXX XXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
                    XXXX XXXX XXXXXX XXX
                    XXXXX
                        XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Search Term') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX
                            XXXXXXXXXXXXX gettext(u'Enter keywords to search...') X
                            XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXX XXXX XXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Content Type') XXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX BB BBB BBBBBBBBBBBBBBBBXXXXXXXBBBBB
                                    XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'All Content') XXXXXXX
                            XXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXBBBBB XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Articles Only') XXXXXXX
                            XXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXBBBBB XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Events Only') XXXXXXX
                            XXXXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXX XXXXXX XXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Category') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'All Categories') XXXXXXXXX
                            BBB BBBBBBBB BB BBBBBBBBBB
                            XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
                                
                            XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX

                    XXXX XXXX XXXXX XXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'From Date') XXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                                XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'To Date') XXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                                XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXX XXXXXXX XXX
                    XXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Sort By') XXXXXXXX
                        XXXXXXX XXXXXXXXXXX XXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                                 gettext(u'Relevance') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Newest First') 
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Oldest First') 
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Most Popular') 
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Featured First') 
                            XXXXXXXXX
                        XXXXXXXXX
                    XXXXXX

                    XXXX XXXXXX XXXXXXX XXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Search') 
                        XXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
                            XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX gettext(u'Clear') 
                        XXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXX XXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Quick Access') XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'All Articles') XXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Browse all news articles') XXXX
                    XXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'All Events') XXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Browse all events') XXXX
                    XXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Upcoming Events') XXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u"See what's coming up") XXXX
                    XXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Featured Content') XXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'See featured articles') XXXX
                    XXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXX XXXXXXXXXX XXX
BB BBBBBBBBBB
XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Browse by Category') XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                BBB BBBBBBBB BB BBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBB
                        XX XXXXXXX XXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXX
                XXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB BBBBBBBB