BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB gettext(u'Remittance Services - Bhanjyang Cooperative') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Send money home safely and affordably with our trusted remittance partners including eSewa, Khalti, IME, Western Union, and more.') BBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBB gettext(u'Remittance, Money Transfer, eSewa, Khalti, IME, Western Union, Bhanjyang Cooperative') BBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
             gettext(u'The Power of Cooperatives - Remittance Services') 
        XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
             gettext(u'Empowering Members and Economic Prosperity. Send money home safely and affordably with our trusted partners.') 
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Contact Us for Remittance Services') 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXX XXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Our Remittance Partners') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                 gettext(u"We partner with Nepal's most trusted remittance service providers to offer you secure, fast, and affordable money transfer options.") 
            XXXX
        XXXXXX

        XXXX XXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
            XXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Digital wallet and payment services') XXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Mobile payment platform') XXXX
                XXXXXX
            XXXXXX

            XXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'International money exchange') XXXX
                XXXXXX
            XXXXXX

            XXXX XXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Digital payment solution') XXXX
                XXXXXX
            XXXXXX

            XXXX XXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Remittance services') XXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Global money transfer') XXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Express money transfer') XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Why Choose Our Remittance Services?') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                 gettext(u'We provide secure, fast, and affordable money transfer services through trusted partners.') 
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Secure Transactions') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'All transactions are encrypted and secure, ensuring your money reaches safely.') XXXX
            XXXXXX

            XXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Fast Transfer') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Quick money transfer with same-day or next-day delivery options.') XXXX
            XXXXXX

            XXXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Competitive Rates') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Low fees and competitive exchange rates for maximum value.') XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXX XX XXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'How It Works') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                 gettext(u'Sending money through our remittance services is simple and straightforward.') 
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXX X XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Visit Our Office') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Come to our cooperative office with your documents.') XXXX
            XXXXXX

            XXXX XXXX X XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Choose Service') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Select your preferred remittance service provider.') XXXX
            XXXXXX

            XXXX XXXX X XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Complete Transaction') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Provide recipient details and complete the transfer.') XXXX
            XXXXXX

            XXXX XXXX X XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Confirmation') XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Receive confirmation and tracking details.') XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Ready to Send Money?') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXX
             gettext(u'Contact us today to learn more about our remittance services and get started with secure money transfers.') 
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Contact Us Now') 
            XXXX
            XX XXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Learn More About Us') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB
