# Generated by Django 5.2.7 on 2025-10-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person submitting the form', max_length=100)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('subject', models.CharField(help_text='Subject of the inquiry', max_length=200)),
                ('message', models.TextField(help_text='Detailed message content')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the submitter')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the submission was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the submission was last updated')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', help_text='Current status of the submission', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the submission was resolved', null=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_con_status_57081e_idx'), models.Index(fields=['email'], name='contact_con_email_394734_idx'), models.Index(fields=['created_at'], name='contact_con_created_0e637d_idx')],
            },
        ),
    ]
