# Generated by Django 5.2.7 on 2025-10-19 20:25

import apps.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to=apps.contact.models.contact_attachment_path),
        ),
    ]
