# Generated by Django 5.2.7 on 2025-10-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsubmission_attachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['ip_address'], name='contact_con_ip_addr_eb6996_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['status'], name='contact_con_status_b337da_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['resolved_at'], name='contact_con_resolve_0198b5_idx'),
        ),
    ]
