# Generated by Django 5.2.9 on 2025-12-15 03:27

import apps.contact.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYMSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(default='Nepali', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('permanent_address', models.CharField(max_length=255)),
                ('district', models.CharField(default='Kaski', max_length=100)),
                ('province', models.CharField(default='Gandaki Province', max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('grand_father_name', models.CharField(max_length=100)),
                ('nominee_name', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('income_source', models.CharField(max_length=100)),
                ('estimated_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('citizenship_front', models.FileField(upload_to=apps.contact.models.kym_document_path)),
                ('citizenship_back', models.FileField(upload_to=apps.contact.models.kym_document_path)),
                ('passport_photo', models.FileField(upload_to=apps.contact.models.kym_document_path)),
                ('address_proof', models.FileField(upload_to=apps.contact.models.kym_document_path)),
                ('income_proof', models.FileField(blank=True, null=True, upload_to=apps.contact.models.kym_document_path)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kym_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYM Submission',
                'verbose_name_plural': 'KYM Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_kym_status_9f3d8d_idx'), models.Index(fields=['email'], name='contact_kym_email_25bea1_idx'), models.Index(fields=['phone'], name='contact_kym_phone_fc3b18_idx'), models.Index(fields=['created_at'], name='contact_kym_created_6585a1_idx')],
            },
        ),
    ]
