# Generated by Django 5.2.9 on 2025-12-19 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_kymsubmission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(fields=["name"], name="contact_con_name_b6655d_idx"),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(fields=["phone"], name="contact_con_phone_fc3312_idx"),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["updated_at"], name="contact_con_updated_c48539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["subject"], name="contact_con_subject_023399_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kymsubmission",
            index=models.Index(
                fields=["full_name"], name="contact_kym_full_na_630dd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kymsubmission",
            index=models.Index(
                fields=["reviewed_by"], name="contact_kym_reviewe_a04ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kymsubmission",
            index=models.Index(
                fields=["updated_at"], name="contact_kym_updated_69cefc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kymsubmission",
            index=models.Index(
                fields=["reviewed_at"], name="contact_kym_reviewe_17960c_idx"
            ),
        ),
    ]
