# Generated by Django 5.2.9 on 2025-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_add_database_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the location (e.g., 'Main Office', 'Polyang Branch')",
                        max_length=200,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Full address of the location", max_length=255
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude coordinate for map display",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude coordinate for map display",
                        max_digits=9,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("main_office", "Main Office"),
                            ("branch_office", "Branch Office"),
                            ("service_center", "Service Center"),
                            ("atm_center", "ATM Center"),
                        ],
                        default="branch_office",
                        help_text="Type of location",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for this location",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for this location",
                        max_length=254,
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        help_text="Operating hours (e.g., '9:00 AM - 5:00 PM', '24/7')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the location and services offered",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image of the location",
                        null=True,
                        upload_to="contact/locations/",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of services offered at this location (e.g., ['Savings', 'Loans'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this location is currently active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Office Location",
                "verbose_name_plural": "Office Locations",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["location_type", "is_active"],
                        name="contact_off_locatio_208422_idx",
                    ),
                    models.Index(
                        fields=["is_active", "order"],
                        name="contact_off_is_acti_8f4d39_idx",
                    ),
                    models.Index(fields=["name"], name="contact_off_name_f62615_idx"),
                ],
            },
        ),
    ]
