# Generated by Django 5.2.9 on 2026-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_add_office_location_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Privacy Policy", max_length=200)),
                (
                    "content",
                    models.TextField(help_text="HTML content of the privacy policy"),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Privacy Policy",
                "verbose_name_plural": "Privacy Policies",
            },
        ),
    ]
