# Generated by Django 5.2.9 on 2026-01-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_privacypolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order to display the FAQ (lowest first)",
                        verbose_name="Order",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
