# Generated by Django 5.2.3 on 2025-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_type', models.CharField(choices=[('medical', 'Medical Relief'), ('education', 'Educational Support'), ('disaster', 'Disaster Relief'), ('welfare', 'Welfare Support'), ('emergency', 'Emergency Assistance')], max_length=20, verbose_name='Relief Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('nepali_title', models.CharField(max_length=200, verbose_name='Nepali Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('benefits', models.TextField(verbose_name='Benefits & Support')),
                ('application_process', models.TextField(blank=True, verbose_name='Application Process')),
                ('required_documents', models.TextField(blank=True, verbose_name='Required Documents')),
                ('contact_info', models.TextField(blank=True, verbose_name='Contact Information')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/relief/', verbose_name='Relief Image')),
                ('icon', models.CharField(default='fas fa-heart', max_length=50, verbose_name='Icon Class (FontAwesome)')),
                ('color', models.CharField(default='bhanjyangred', max_length=20, verbose_name='Color Theme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Relief',
                'verbose_name_plural': 'Member Relief Programs',
                'ordering': ['relief_type', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='loantype',
            options={'ordering': ['-is_featured', 'loan_category'], 'verbose_name': 'Loan Type', 'verbose_name_plural': 'Loan Types'},
        ),
        migrations.AlterModelOptions(
            name='savingsaccount',
            options={'ordering': ['-is_featured', 'interest_rate', 'account_type'], 'verbose_name': 'Savings Account', 'verbose_name_plural': 'Savings Accounts'},
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='icon',
            field=models.CharField(default='fas fa-certificate', max_length=50, verbose_name='Icon Class (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='color',
            field=models.CharField(default='bhanjyangred', max_length=20, verbose_name='Color Theme'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='icon',
            field=models.CharField(default='fas fa-hand-holding-usd', max_length=50, verbose_name='Icon Class (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Product'),
        ),
        migrations.AddField(
            model_name='remittanceservice',
            name='icon',
            field=models.CharField(default='fas fa-exchange-alt', max_length=50, verbose_name='Icon Class (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='color',
            field=models.CharField(default='deuraligreen', max_length=20, verbose_name='Color Theme'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='features',
            field=models.TextField(blank=True, verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='icon',
            field=models.CharField(default='fas fa-piggy-bank', max_length=50, verbose_name='Icon Class (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Product'),
        ),
    ]
