# Generated by Django 5.2.7 on 2025-10-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='core_securi_event_t_195db6_idx',
            old_name='coop_securi_event_t_535be1_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='core_securi_ip_addr_7d786f_idx',
            old_name='coop_securi_ip_addr_043306_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='core_securi_timesta_8b537b_idx',
            old_name='coop_securi_timesta_cfb969_idx',
        ),
    ]
