# Generated by Django 5.2.9 on 2026-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_rename_coop_securi_event_t_535be1_idx_core_securi_event_t_195db6_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("contact", "Contact Page"),
                            ("about_intro", "About Introduction"),
                            ("about_cooperative", "About Cooperative"),
                            ("about_board", "About Board"),
                            ("about_management", "About Management"),
                            ("about_timeline", "About Timeline"),
                            ("services_overview", "Services Overview"),
                            ("downloads", "Downloads"),
                            ("gallery", "Gallery"),
                        ],
                        help_text="Select the page for SEO settings",
                        max_length=50,
                        unique=True,
                        verbose_name="Page",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Page-specific SEO title. If empty, falls back to site_info.meta_title or default.",
                        max_length=200,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Page-specific SEO description. If empty, falls back to site_info.meta_description or default.",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO. If empty, falls back to site_info.meta_keywords or default.",
                        max_length=500,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Title for social media sharing. If empty, uses meta_title.",
                        max_length=200,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True,
                        help_text="Description for social media sharing. If empty, uses meta_description.",
                        max_length=500,
                        verbose_name="Open Graph Description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended). If empty, uses site_info.og_image.",
                        null=True,
                        upload_to="seo/page_og_images/",
                        verbose_name="Open Graph Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active SEO settings are used.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page SEO",
                "verbose_name_plural": "Page SEO Settings",
                "ordering": ["page"],
            },
        ),
    ]
