BBBB BBBBBB
BBBB BBBB
 #
 #
 #
 #


BB BBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXX XXX XXXXX XXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX XXXXXX X  gettext(u'Board of Directors') XX
    XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX X XXXXX XX XXXXXXXXXXX
    XXXXXXXXXXXXXX X gettext(u'Elected leadership and governance committees of Bhanjyang Saving & Credit Cooperative Society Ltd.') XX
    XXXXXX XXX
    XXXXXXXXX X
        BBB BBBBBBBBB BB BBBBBBBBBB
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBB
        X
            XXXXXXXX XXXXXXXXX
            XXXXXXX XFFFFFFFFXX
            XXXXXXXXXXX XFFFFFFFFXX
            XXXXXXXXXXX X
                XXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXX XFFFFFFFFXX
                XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX
            XX
            XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXBB BBBBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXX XXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXX XXXXXBBBBB
        XBB BBB BBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBXBBBBB
        BBBBB
        BBBBBB
        BBBBBB
    X
X
XXXXXXXXX

XXXX XXXXXXXXXX XXXXXX XXXXXXX XXX XXX XXXXXXXXX XXX
BBB BBBBBBBBB BB BBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBB
BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXXX XFFFFFFFFXX
    XXXXXXXXXXX XFFFFFFFFXX
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
    XX
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX XFFFFFFFFXX
        XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX
    XX
    BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXBBBBB
    XXXXXX XX
X
XXXXXXXXX
BBBBB
BBBBBB
BBBBB
BBBBBB
BBBBB

XXXX XXXXXXXXXXXXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'Home') XX
            XXXXXXX XXXXXX
        XX
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'About Us') XX
            XXXXXXX XXXXBBB BBBBBBBBBBBBBBBBBBBBX
        XX
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'Board of Directors') XX
            XXXXXXX XX
        X
    X
X
XXXXXXXXX

