BBBB BBBBBB
BBBB BBBB
 #
 #
 #
 #


BB BBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXX XXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX XXXXXX X  gettext(u'Management Team') XX
    XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX X gettext(u'Professional staff members who handle day-to-day operations and member services at Bhanjyang Saving & Credit Cooperative Society Ltd.') XX
    XXXXXX XXX
    XXXXXXXXXXX X
        BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBB
        X
            XXXXXXXX XXXXXXXXX
            XXXXXXX XFFFFFFFFXX
            XXXXXXXXXXX XFFFFFFFFXX
            XXXXXXXXXXX X
                XXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
                XXXXXX XXXXXX
            XX
            BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX XFFFFFFFFXXBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX XXXBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX XX
        XBB BBB BBBBBBBBBBBBXBBBBB
        BBBBBB
    X
X
XXXXXXXXX

XXXX XXXXXXXXXX XXXXXX XXXXXXX XXX XXX XXXXX XXXXXXX XXX
BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBB BB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXXX XFFFFFFFFXX
    XXXXXXXXXXX XFFFFFFFFXX
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXXX
        XXXXXXX X
            XXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX
        X
    XX
    BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX XFFFFFFFFXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX XXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXBBBBB
    XXXXXX XX
X
XXXXXXXXX
BBBBB
BBBBBB
BBBBB

XXXX XXXXXXXXXXXXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'Home') XX
            XXXXXXX XXXXXX
        XX
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'About Us') XX
            XXXXXXX XXXXBBB BBBBBBBBBBBBBBBBBBBBX
        XX
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'Management Team') XX
            XXXXXXX XX
        X
    X
X
XXXXXXXXX

