BBBB BBBBBB
BBBB BBBB
 #
 #
 #
 #


BB BBBBBBBB
XXXX XXXXXXXX XXXXXX XXX XXXXXXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXX
    XXXXXXX X gettext(u'Bhanjyang Cooperative Timeline') XX
    XXXXXXXXXXXXXX X gettext(u'Key milestones, achievements, and events in the history of Bhanjyang Saving & Credit Cooperative Society Ltd.') XX
    XXXXXXXXXXXXXXXXXX X
        BBB BBBBB BB BBBBBBBB
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX X
            XXXXXXX X
                XXXXXXXX XXXXXXXX
                XXXXXXX XFFFFFFFFXX
                XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
                XXXXXXXXXXXX XFFFFFFFFXX
                XXXXXXXX XBB BBBBBBBBBBBXXXBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                XXXXXXXXXXXX X
                    XXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
                    XXXXXX XXXXXX
                XX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XBB BBB BBBBBBBBBBBBXBBBBB
        BBBBBB
    X
X
XXXXXXXXX

XXXX XXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXXX XXXXXXX XXX
BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXX
    XXXXXXX XFFFFFFFFXX
    XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
    XXXXXXXXXXXX XFFFFFFFFXX
    XXXXXXXX XBB BBBBBBBBBBBXXXBBBBXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXXX
        XXXXXXX X
            XXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX
        X
    XX
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXX
        X
    XX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXX
X
XXXXXXXXX
BBBBB
BBBBBB
BBBBB

XXXX XXXXXXXXXXXXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'Home') XX
            XXXXXXX XXXXXX
        XX
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'About Us') XX
            XXXXXXX XXXXBBB BBBBBBBBBBBBBBBBBBBBX
        XX
        X
            XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XX
            XXXXXXX X gettext(u'Timeline') XX
            XXXXXXX XX
        X
    X
X
XXXXXXXXX

