# Generated by Django 5.2.3 on 2025-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='शीर्षक', max_length=200)),
                ('description', models.TextField(blank=True, help_text='छोटो विवरण')),
                ('file', models.FileField(help_text='अपलोड गर्ने फाइल', upload_to='downloads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='अपलोड गरिएको मिति')),
                ('file_type', models.CharField(blank=True, help_text='फाइलको प्रकार (उदाहरण: pdf, docx, xlsx)। यदि खाली छोडियो भने, फाइल एक्सटेन्सनबाट अनुमान गरिनेछ।', max_length=10)),
            ],
            options={
                'verbose_name': 'डाउनलोड फाइल',
                'verbose_name_plural': 'डाउनलोड फाइलहरू',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
