# Generated by Django 5.2.7 on 2025-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FRM', 'Application Form'), ('RPT', 'Financial Report'), ('PCY', 'Policy & Bylaw'), ('PUB', 'Publication'), ('OTH', 'Other Document')], default='OTH', help_text='फाइलको श्रेणी (जस्तै: फारम, रिपोर्ट)।', max_length=3)),
                ('title', models.CharField(help_text='फाइलको शीर्षक।', max_length=200)),
                ('description', models.TextField(blank=True, help_text='फाइलको संक्षिप्त विवरण।')),
                ('file', models.FileField(help_text='अपलोड गर्ने फाइल।', upload_to='downloads/')),
                ('is_active', models.BooleanField(default=True, help_text='यो फाइल वेबसाइटमा देखाउने कि नदेखाउने?')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, help_text='यो फाइल कति पटक डाउनलोड भयो।')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(blank=True, editable=False, help_text='फाइलको प्रकार (स्वचालित रूपमा पत्ता लगाइन्छ)।', max_length=10)),
            ],
            options={
                'verbose_name': 'डाउनलोड फाइल',
                'verbose_name_plural': 'डाउनलोड फाइलहरू',
                'ordering': ['-uploaded_at'],
                'get_latest_by': 'uploaded_at',
            },
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
