# Generated by Django 5.2.7 on 2025-10-19 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_downloadablefile_delete_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadablefile',
            options={'get_latest_by': 'uploaded_at', 'ordering': ['-priority', '-uploaded_at'], 'verbose_name': 'डाउनलोड फाइल', 'verbose_name_plural': 'डाउनलोड फाइलहरू'},
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='फाइलको समाप्ति मिति (वैकल्पिक)।', null=True),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='यो फाइल फिचर्ड सूचीमा देखाउने?'),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low Priority'), ('MED', 'Medium Priority'), ('HIGH', 'High Priority'), ('URG', 'Urgent')], default='MED', help_text='फाइलको प्राथमिकता स्तर।', max_length=4),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='requires_login',
            field=models.BooleanField(default=False, help_text='यो फाइल डाउनलोड गर्न लगइन आवश्यक छ?'),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='tags',
            field=models.CharField(blank=True, help_text='फाइलका ट्यागहरू (कमा द्वारा अलग)।', max_length=500),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='फाइलको थम्बनेल छवि (वैकल्पिक)।', null=True, upload_to='downloads/thumbnails/'),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='यो फाइल कति पटक हेरियो।'),
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='category',
            field=models.CharField(choices=[('FRM', 'Application Form'), ('RPT', 'Financial Report'), ('PCY', 'Policy & Bylaw'), ('PUB', 'Publication'), ('MAN', 'User Manual'), ('CERT', 'Certificate'), ('BRO', 'Brochure'), ('OTH', 'Other Document')], default='OTH', help_text='फाइलको श्रेणी (जस्तै: फारम, रिपोर्ट)।', max_length=4),
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='file',
            field=models.FileField(help_text='अपलोड गर्ने फाइल।', upload_to='downloads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddIndex(
            model_name='downloadablefile',
            index=models.Index(fields=['category', 'is_active'], name='downloads_d_categor_0ca7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadablefile',
            index=models.Index(fields=['priority', 'is_featured'], name='downloads_d_priorit_4e95c0_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadablefile',
            index=models.Index(fields=['uploaded_at'], name='downloads_d_uploade_f68532_idx'),
        ),
    ]
