# Generated by Django 5.2.7 on 2025-10-19 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_alter_downloadablefile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablefile',
            name='access_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of times this file has been accessed.'),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA-256 hash of file content for security tracking.', max_length=64),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time this file was accessed.', null=True),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
