# Generated by Django 5.2.7 on 2025-10-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/albums/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent_album', models.ForeignKey(blank=True, help_text='Leave blank for root album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_albums', to='home.galleryalbum')),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Album this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.galleryalbum'),
        ),
    ]
