# Generated by Django 5.2.9 on 2025-12-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_galleryalbum_galleryimage_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
