# Generated by Django 5.2.9 on 2026-01-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_galleryimage_album_delete_galleryalbum_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceHighlight",
        ),
    ]
