# Generated by Django 5.2.9 on 2026-01-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_delete_servicehighlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="primary_button_text",
            field=models.CharField(
                blank=True,
                help_text="Primary button text (e.g., 'Explore Services')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="primary_button_url",
            field=models.CharField(
                blank=True,
                help_text="Primary button URL (e.g., '/services/')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="secondary_button_text",
            field=models.CharField(
                blank=True,
                help_text="Secondary button text (e.g., 'Contact Us')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="secondary_button_url",
            field=models.CharField(
                blank=True,
                help_text="Secondary button URL (e.g., '/contact/')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero background image for slider",
                null=True,
                upload_to="home/hero/",
            ),
        ),
    ]
