# Generated by Django 5.2.9 on 2026-01-18 05:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("home", "0005_add_hero_button_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this announcement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this announcement was actually published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this announcement to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_homepage_contents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this content was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this content to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this statistic",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_statistics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this statistic was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this statistic to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this testimonial",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_testimonials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this testimonial was published",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule this testimonial to be published at a specific date/time",
                null=True,
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[
                    ("DF", "Draft"),
                    ("PB", "Published"),
                    ("SC", "Scheduled"),
                    ("AR", "Archived"),
                ],
                default="DF",
                help_text="Publication status",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="publish_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Original publish date",
                verbose_name="Publish Date",
            ),
        ),
        migrations.CreateModel(
            name="ContentVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "variant_name",
                    models.CharField(
                        help_text="e.g., 'Variant A', 'Variant B'",
                        max_length=100,
                        verbose_name="Variant Name",
                    ),
                ),
                (
                    "variant_data",
                    models.JSONField(
                        default=dict,
                        help_text="Store variant-specific data (title, description, etc.)",
                        verbose_name="Variant Data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this variant currently active?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this variant was viewed",
                        verbose_name="Views",
                    ),
                ),
                (
                    "conversions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of conversions (clicks, signups, etc.)",
                        verbose_name="Conversions",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Variant",
                "verbose_name_plural": "Content Variants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="home_conten_content_8c9a6b_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="home_conten_is_acti_465a4e_idx"
                    ),
                ],
            },
        ),
    ]
