# Generated by Django 5.2.9 on 2026-01-18 05:16

from django.db import migrations
import django.utils.timezone


def convert_is_active_to_status(apps, schema_editor):
    """Convert existing is_active=True to status=PUBLISHED"""
    HomePageContent = apps.get_model('home', 'HomePageContent')
    Testimonial = apps.get_model('home', 'Testimonial')
    Statistic = apps.get_model('home', 'Statistic')
    Announcement = apps.get_model('home', 'Announcement')
    
    now = django.utils.timezone.now()
    
    # Convert HomePageContent
    HomePageContent.objects.filter(is_active=True).update(
        status='PB',  # PUBLISHED
        published_date=now
    )
    
    # Convert Testimonial
    Testimonial.objects.filter(is_active=True).update(
        status='PB',  # PUBLISHED
        published_date=now
    )
    
    # Convert Statistic
    Statistic.objects.filter(is_active=True).update(
        status='PB',  # PUBLISHED
        published_date=now
    )
    
    # Convert Announcement
    Announcement.objects.filter(is_active=True).update(
        status='PB',  # PUBLISHED
        published_date=now
    )


def reverse_convert(apps, schema_editor):
    """Reverse migration: set is_active based on status"""
    HomePageContent = apps.get_model('home', 'HomePageContent')
    Testimonial = apps.get_model('home', 'Testimonial')
    Statistic = apps.get_model('home', 'Statistic')
    Announcement = apps.get_model('home', 'Announcement')
    
    # Set is_active=True for PUBLISHED items
    HomePageContent.objects.filter(status='PB').update(is_active=True)
    Testimonial.objects.filter(status='PB').update(is_active=True)
    Statistic.objects.filter(status='PB').update(is_active=True)
    Announcement.objects.filter(status='PB').update(is_active=True)
    
    # Set is_active=False for others
    HomePageContent.objects.exclude(status='PB').update(is_active=False)
    Testimonial.objects.exclude(status='PB').update(is_active=False)
    Statistic.objects.exclude(status='PB').update(is_active=False)
    Announcement.objects.exclude(status='PB').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_announcement_published_by_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_is_active_to_status, reverse_convert),
    ]
