# Generated by Django 5.2.9 on 2026-01-18 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_convert_is_active_to_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="auto_expire",
            field=models.BooleanField(
                default=False,
                help_text="Automatically archive this announcement when expiry_date is reached",
                verbose_name="Auto Expire",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "is_featured", "-priority"],
                name="ann_status_feat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "scheduled_date"], name="ann_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "expiry_date"], name="ann_status_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepagecontent",
            index=models.Index(
                fields=["status", "order"], name="home_status_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepagecontent",
            index=models.Index(
                fields=["status", "scheduled_date"], name="home_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepagecontent",
            index=models.Index(
                fields=["status", "published_date"], name="home_status_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statistic",
            index=models.Index(
                fields=["status", "is_featured", "order"], name="stat_status_feat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statistic",
            index=models.Index(
                fields=["status", "scheduled_date"], name="stat_status_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["status", "is_featured", "order"], name="test_status_feat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["status", "scheduled_date"], name="test_status_sched_idx"
            ),
        ),
    ]
