BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXX X XXXXXXXXX XXXXXXXXXXX XXXXXBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXX XXX XXXXXX XXXXXX
                XXXXXX
            BBBBB
            
            BB BBBBBBBBBBBBBBBBBBBBB
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                BBBBBB
            BBBBB
            
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBXX
                BBBBBBBBBB
                
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXX
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXX
                    XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX XX
                    XXXXXXXX
                XXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XX
                XXXXXXXXX
                
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XX XXXXXXX
                XXXX
            XXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
