BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBB gettext(u'Bhanjyang Cooperative - Download Center') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB gettext(u'Download important forms, documents, and resources from Bhanjyang Saving & Credit Cooperative Society Ltd. Access our downloadable files, policies, and applications.') BBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBB gettext(u'Bhanjyang Cooperative, Download, Downloadable Files, Forms, Documents, Resources, Policies, Applications, PDF, Word, Excel') BBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Download Center - Bhanjyang Cooperative') BBBBBBBB
BBBBB BBBBBBBBBBBBBB gettext(u'Download important forms, documents, and resources from Bhanjyang Cooperative') BBBBBBBB
BBBBB BBBBBBBXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX

XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX X gettext(u'Download Center') XX
    XXXXXXXXXXXXXX X gettext(u'Download important forms, documents, and resources from Bhanjyang Cooperative') XX
    XXXXXX XXX
    XXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
    XX
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX X
            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
            X
                XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX XFFFFFFFFXX
                XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFXX
                XXXXXXXXXXXXXXXXX XFFFFFXX
                XXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXX XFFFFFFFFFFFFX
            XBB BBB BBBBBBBBBBBBXBBBBB
            BBBBBB
        X
    X
X
XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXX
XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
     gettext(u'Skip to main content') 
XXXX

XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Download Center') 
        XXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
             gettext(u'Available Resources') 
        XXXXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Access important documents, forms, and resources from our cooperative. Download files instantly and stay updated with our latest materials.') 
        XXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXX XXX XXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Search and Filter Downloads') XXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Search and filter downloadable files') XX
            BBBBBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Category') 
                    XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX gettext(u'All Categories') XXXXXXXXX
                        BBB BBBBBBBBBB BB BBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBX
                        XXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Priority') 
                    XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX gettext(u'All Priorities') XXXXXXXXX
                        BBB BBBBBBBBBB BB BBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBX
                        XXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Search Files') 
                    XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Search by title, description, or tags...') X XXXXXXXX
                            XXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBXXXXXXXBBBBB
                            XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Featured Only') 
                        XXXXXXX
                    XXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXX gettext(u'Search for files') XX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Search Files') XXXXXXX
                XXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Reset Filters') XXXXXXX
                XXXX
            XXXXXX
        XXXXXXX

        XXXX XXXX XXXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                     gettext(u'Bulk Download') 
                XXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Select all files for bulk download') XX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Select All') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Clear all selections') XX
                        XX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Clear All') 
                    XXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'files selected') XXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Download Selected') XXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXX XXXXXXX XXX
BB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXXX XXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB

XXXX XXXXX XX XXXXXXXX XXXXXXX XXX
BB BBBBBBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
        BBB BBBBBBBBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                        BB BBBBBBBBBBBBB BB BBBBB
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB BB BBBBB
                        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB BB BBBBB
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB BB BBBBB
                        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB BB BBBBB
                        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB BB BBBBBB
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB BB BBBBB
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                    XXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                BBBBBB
            XXXXXX

            BB BBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXX X XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
        BBBBBB

        XXXX XXXXXX XXXX XXX XXXXXX XXX
        BB BBB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXBB BBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBBB BXXXBBBBBXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBB BB BXBB BBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBBB BXXBBBBBBBBBBX
                XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        BBBBB
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXX
                    XXXX XXXXXX XX XXXXXX XXXXXXXX XX XXXXXXXX XXX XXXXXXXXX XXXX XXXXXXXX XX XXXXX XXX XXXXXXX XX XXX XXX XXXXXXXXX XXXXXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXX
            XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                XXXXXXXX XXXXXX XXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXX XXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXXXX XXX XXXXXXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXFFFFFFXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
