BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBXXXXXXXX XXXXXXX X XXXXXXXXX XXXXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBXXXX XXXX XXXXXXXX XXXXXXX XXX XXXXX XXXX XXXXXXXXXX XXXXX XXXX XXXXXXXXX XXXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
    X
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXX X X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
    X
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXX XXXXXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        XXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXX XXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBB
                BBB BBBBBBBB BB BBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFFFFFFFXX
                            BB BBBBBBBBBBBBBBBBBB BB BBBBB
                                X
                            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
                                X
                            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
                                X
                            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
                                XX
                            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                                XX
                            BBBB
                                X
                            BBBBB
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                                XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXFFFFFFF FF FFXXXXXXX
                                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXFFFFFFFFFFXXXXXXX
                                XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBB
                                    XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXFFFFFXXXXXXX
                                BBBBB
                            XXXXXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX 
                               XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX
                            XXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX 
                               XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            BBBB
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXX XXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX 
                       XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXXXXX
                    XXXX
                XXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX 
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXX XX XXXXXXXXX
            XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXXX XXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXX XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            
            XX XXXXXX XXXXXX XXX
            XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXX XXX XXXXX XX 
                    XXXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXX XX
                    XXXXXXX XXX XXXXXXX XX XXXXXXXX XXX XXXXXXX XX
                    XXXXXXX XXX XXXXXXXXX XX XXXXXXXX XXX XXXXXXXXX XX
                    XXXXXXX XXX XXXXXXXXXX XX XXXXXXXX XXX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            XXX
        XXX
    XXX
XXX

XXXXXXXX XXXXXXXXXXXXXX X
    XX XXXXX XX XXXXXXXX XXX XXXXXX XXXX X XXXX
    XXXXX XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXX X XXX XXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXX X XX X XX X XXXXX
    XXXXXX XXXXXXXX XX XX
X

XXXXXXXX XXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXX XXX XXXX XXX XXXX XX XXXXX XXXX XXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXX XX XXXXXXXXXX X
        XX XXXX XXXXX XXXXXXXXX XXXX XX XXXX XXXXXXX XX XXXXX XXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    X
X

XX XXX XXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXX XXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    X
XXX
XXXXXXXXX
BBBBBBBB
