BBBB BBBBBB
BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX X XXXXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
    XXXXXXX
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXX XX XXXXXXXXX
        X
        XXXXXXXXXX XXXXX X
            XXX XXXX X
                XXXXXXXXXX XXXXXXXXX
            X
            XXX X
                XXXXXXXXXX XXXXXXXXXXXX
            X
        X
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXX
            XXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXX X XXXXX XXX XX
                XXXXXX
            XXXXXX
            
            XXXX XXXXX XXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            
            XXXX XXXXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
            
            XXXX XXXXXX XXXX XXX
            BB BBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXX
                XXXXXX XXXX 
            XXXX
            BBBBB
            
            XXXX XXXXXXX XXXXXXX XXX
            BB BBBBBBBBBBB BB BBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXX X X X X XXXX XXXXXXXXX X X XXXX X X X X XXX XXXX XXX X X XXX XXXXX X X XXX XXXXX X X XXXXXXXXXX X X XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    XXXXX XXXXXX
                XXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXX XXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX
                XXXXX
            XXXXXX
            BBBB BBBBBBBBBBB BB BBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXXXX X X X XXX XXXXXXXXX XXXXXXX X X XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX X X XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    XXXX XXXXXXXXX
                XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXX XXX XXXXXX XXXX XXXXXX XXXXXXXXXX
                XXXX
            XXXXXX
            BBBBB
            
            XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX 
                   XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXX XX
                    XXXXXX
                    XXXXXXX XXXXXXX XXXXXXXXXX
                XXXX
                
                XX XXXXXXXX 
                   XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX X XXX XXXXXXX X X XXX XXXXXXXXXXX XXXXXXXXXXX X X XXXX XXXXXXX XXX X X XXXXXXXXXX X X XXXXXXXXX X X XXX XXXXX X X XXX XXXX XXXX XX
                    XXXXXX
                    XXXXXXXX
                XXXX
            XXXXXX
            
            XXXX XXXXXXX XXXX XXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXX XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
