BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBB X XXXXXXX X XXXXXXXXX XXXXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFBBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBX X XXXXXXXX XXXXXXXXX XXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXX XXXX XX
    X
    XXXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXX XXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
    X
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX X
    
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXX XXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
        XXXXXXXXXXX XXXXX
    X
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXX XX X
            XXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXX XX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        FFFFF
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX
        XXXX XXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
                    BB BBBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            X XXXXXXXX
                        XXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            X XXXXX XXXXXXXX
                        XXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            X XXXXXXX
                        XXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            
            BB BBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            BBBBB
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
            XXXXXX
            
            BB BBBBBBBBB
                XXXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
                        BBB BBB BB BBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBB BB BBBBB
                XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXX
                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXXXX
            BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXX XX XXXXXXXXX XX XXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            BBBBB
            
            XXXX XXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXX XXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XX XXXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXXXXXX XXXXXX XXX XXXXXX XXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX X
        XX XXX XXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX X XXXX
        XXX
        
        XX XXX XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXX
    X
XXX

XX XXX XXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXX XXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    X
    XX XXXXXX XXX XXX XX XXXXXXXXXX XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX
    X
XXX
XXXXXXXXX
BBBBBBBB
