BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBB

XXXXXXX
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XX X
        XXXXXXX X X XXXX XX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X X
        XXXXXXX X X XXXX XX
        XXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXX XX X
        XXXXXXX X X XXXXXX XX
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXXXXX
        XXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBBBBB
XXXX XXXX XXXXXX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXXXXXXX XXXXXXXX XXXXXX XX XXXX XXXX XXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX
    XXXX
XXXXXX

XXXX XXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX
        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXX
        XXXX
        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
    XXXXXX
XXXXXX
BBBBB


BBBBBBBB
