BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXX X XXXXXX XXXXXXXXX X BBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        X
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXX X
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX X XXXXXX XXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXX
XXXXXX

XXXX XXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XX XXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXX XXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
    XXXX XXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBB
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFF FF FFXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBB
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB B B
                        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX
                    BBBB
                        XX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXX XXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X FFFFX
    
    XXX XXXXXXXXXXXXXXXX X
        XXXXX XXXXXXX
        XXXXX X
            XXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
            XXXXXXXXX XX
                XXXXXX XXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXXX
                XXXXXXXX XXX
            XX X
                XXXXXX XXXXXX XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXX XXXXXX
                XXXXXXXX XXX
            XX
        XX
        XXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXX X
                XX X
                    XXXXXXXXXXXX XXXX
                X
            X
        X
    XXX
    
    XX XXXXXXXX XXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X FFFFX
    
    XXX XXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXX
        XXXXX X
            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
            XXXXXXXXX XX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X
                    XXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXX
                X
            XX
        XX
        XXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXX X
                XXXXXXX X
                    XXXXXXXXX XXXXXXXX
                X
            X
        X
    XXX
XXX
XXXXXXXXX
BBBBBBBB
