BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXXX XXXXXXXXX X XXXXXXXX XXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBXXX XXXXX XXXX XXXXXXXXXX XX XXXXXX XXXX XXXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX
        XXXXX
            XXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXX XXXX XXXXXXXXXX XX XXXXXX XXXX XXXXXXXXX
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBX 
               XXXXXXXXXXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X X XXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXX X X XXXXXXX XXXXXXXXXXX XXXXXX X X XXX XXXXXXXXXXXXX XXXXXXX X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                XXXXXXX
                XX XXXX XXXX
            XXXX
            
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXX XXXXXXX XXX XXXXXX XXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB
