BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXXX XXXXX X XXXXXXXXX XXXXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                XXXXXX XXXXXXXXX XXXX XXXXX XX XXX XXXX XXX XXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXXX XXXXXXXX XXX XX XXXXXXX XX XXXXXXX XXX XXXXXX
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBX 
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                XXXXXX XX XXXXXXXX
            XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                XXXXXX XXX XXXXX XX X XXX XXXXXXXX XX XXX XXXXXXX XXXXXXXXX XXXX XXXX XX 
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XX
                XXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB
