BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBB

XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXX X X XXXX XX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXX X X XXXXXX XX
        XXXXXXXX XXXX
        XXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXXX
        XXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXX XXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X X
        XXXXXXXXXX XXXXXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXX XXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXX XXXXXX XX XXXXXXXX XXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX X XXXX XXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXX
XXXXXX


BBBBBBBB
