# Generated by Django 5.2.3 on 2025-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='read_time',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Estimated read time in minutes'),
        ),
    ]
