BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Advanced Search - Bhanjyang Cooperative') BBBBBBBB BBBBB

BBBBB BBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXX XXXXXXX XXX XXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXX XXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    
    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Advanced Search') 
            XXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u"Find exactly what you're looking for across all our content") 
            XXXX
        XXXXXX
    XXXXXXXXXX

    XXXX XXXXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search for anything...') X
                        XXXXXXXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                    
                    XXXX XXXXXXX XXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                         gettext(u'Search') 
                    XXXXXXXXX

                    XXXX XXXXXXXXXXX XXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX 
                         XXXXXXXXXXXXXXXXXXXXXXXX X XXX
                         XXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX
                                XXXXX
                            XXXXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXX XXXXXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Search Type') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXX gettext(u'All Content') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX gettext(u'Team Members') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXX gettext(u'Timeline Events') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Affiliations') XXXXXXXXX
                        XXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Sort By') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Relevance') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX gettext(u'Date') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX gettext(u'Title') XXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXXXXXX

    XXXX XXXXXX XXXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Start your search') XXXXX
                XXX gettext(u'Type keywords above to search team members, events, and more.') XXXX
            XXXXXX

            XXXX XXXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Search Results') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                    
                    XXXX XXXXX XXXX XXXXXX XXX
                    XXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Search Tips') 
                    XXXXXXXXX
                XXXXXX

                XXXX XXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXXXX XXX XXXX XXXX XXXX XXXXXXXXXXXXX
                        XXXXXXX XXXXX XXXXXXX XXXXX XX XXXXXXXX XXXX XXXXXXXXXX
                        XXXXXXXXXX XX XXXXX XXXXXXXXX XX XXXXX XXXXXXXXXXX
                    XXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXX XX XXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                            XXXX XXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX

                            XXXX XXXXXXX XXX
                            XXXX XXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX

                                XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

                                XXXX XXXX XXXX XXX
                                XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXX
                                        XX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX

                                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX
                                    XXXXXXXXXXX
                                XXXXXX
                            XXXXXX

                            XXXX XXXXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                                     gettext(u'View Details')  XX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXXXXXXX
            XXXXXX

            XXXX XXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXX XX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'No results found') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX gettext(u"We couldn't find any matches for your search.") XXXX
                XXXXXXX XXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Clear search and try again') XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX
                XXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX 
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Previous') 
                XXXXXXXXX
                
                XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX 
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                     gettext(u'Next')  XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXX
            XXXXXX

        XXXXXX
    XXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXX
    XXXXXX X XXXXXXXXXXXXX X XXXX XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXXXXXXX XX XX XX
            XXXXXX XFFFFFFFFX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
            XXXXX XFFFFFFFFFFFFFFFFFFFFFXX
            XXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
            XXXXXXXX XXX
            XXXXXXXXXXXXX XX
            XXXXX XX
            XXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXX
            XXXXXXXXX XXXXXX

            XXXXX XXXXXX X
                XX XXXXXXXXXXXX X
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX
                X
            XX

            XXXXX XXXXXXXXXXXXXXXXXX X
                XX XXXXXXXXXXXXXXXXXX XX XX X
                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXX
                X XXXX X
                    XXXXXXXXXXXXXXXX X XXX
                X
            XX

            XXXXX XXXXXXXXXXXXXXXXXX X XX X
                XXXXXXXXXXXXXX X XXXXX
                XXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXX X XXX XX XXXXX XXXXXXXXXXX XX XXXXXX

                XXX X
                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX X XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

                    XX XXXXXX XXX
                    XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX

                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
                    XX XXXXXXX XXXXX XXXXXXXX XX XXXXXX XXX XXXX XXXXX XX XXXXX XXXX
                X XXXXXXX X
                    XXXXXXXXXXXXXX X XXXXXX
                    XX XXXXXX XX XXXXXXX XXX XX XXX XXXXXXX XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX
                    X
                X
            XX

            XXXXXXXXXXXXXX XXXXXXX X
                XX XXXXXXX XXXXXX XXX
                XX XXXXX XXXX XXXX XXXXX
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXX
                XXXXX XXXXX X XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XXX
                XXXXXX XXXXXXXXXXXX X XXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXX X XXXXX X XXXXXX
            XX

            XXXXXXXXXXXXXXXXXXX X
                XX XXXXXXXXXXXX XX XXXXXX XXXXXX XXXXX
                XX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX

            XXXXXXXXXXXXXXXXXX X
                XXXXX XXX X X
                    XXXXXXXXXXXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XX
                    XXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XX
                    XXXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXX X
                XX
                XXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXX
            XX

            XXXXXXXXXXXXXXXXXX X
                XXXXX XXX X X
                    XXXXXXXXXXXXXXXXXX X gettext(u'Company Info') XX
                    XXXXXXXXXXXXXXXXXXXXXX X gettext(u'Timeline Event') XX
                    XXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'Affiliation') XX
                    XXXXXXXXXXXXXXXXXXXX X gettext(u'Leadership') XX
                    XXXXXXXXX X gettext(u'Team Member') X
                XX
                XXXXXX XXXXXXXXX XX X gettext(u'Content') XX
            XX

            XXXXXXXXXXXXXXX X
                XX XXXXXXXXX XXXXXXXXXX X XXXXXXXXXX X XXX
                XXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
            XX

            XXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXXXXXXXXXX XXXXXX XXX
                XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXX
                XXX
            X
        XXXX
    XXX
XXXXXXXXX
BBBBBBBB BBBBBBBB